<?php
require_once __DIR__.'/scenario.php';
$__scenario_header=scenario_state();
$__all_flags = all_flags_obtained();
?>
<?php
if (!isset($pageTitle)) $pageTitle = 'INTERAFAS';
if (session_status() !== PHP_SESSION_ACTIVE) { session_start(); }
$current = basename($_SERVER['PHP_SELF']);
lab_page_view($current, (string)$pageTitle);
$servicePages = ['agua-potable.php','alcantarillado.php','saneamiento.php'];
$citizenPages = ['tramites.php','reportes.php','pago.php','panel.php','perfil.php','expediente.php','documentos.php','cultura-agua.php','facturacion.php','factura.php','comprobante.php','notificaciones.php','registro.php','vincular-servicio.php','mis-servicios.php','lectura-medidor.php','afectaciones.php'];
$institutionPages = ['quienes-somos.php','infraestructura.php','organizacion.php','directorio.php','prensa.php','redes-sociales.php','transparencia.php','observatorio.php','contacto.php','informes.php','system.php'];
$isLogged = !empty($_SESSION['user']);
function navActive(array $pages, string $current): string { return in_array($current, $pages, true) ? ' is-active' : ''; }
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Portal institucional de INTERAFAS."><title><?= htmlspecialchars($pageTitle) ?> | INTERAFAS</title><link rel="stylesheet" href="/assets/style.css"></head><body>
<a class="skip-link" href="#contenido">Saltar al contenido</a>
<div class="utility-bar"><div class="wrap utility-inner"><div class="utility-left"><span class="utility-item"><span class="live-dot"></span> Operación metropolitana normal</span><span class="utility-separator"></span><span class="utility-item">Centro de atención 24/7 · 800 123 9000</span></div><div class="utility-right"><a href="/observatorio.php">Datos y estadísticas</a><a href="/afectaciones.php">Afectaciones</a><a href="/reportes.php">Reportar incidencia</a><a href="/contacto.php">Contacto</a></div></div></div>
<header class="site-header"><div class="wrap header-main"><a class="brand" href="/index.php"><span class="brand-symbol"><span class="drop"></span></span><span class="brand-copy"><strong>INTERAFAS</strong><small>Agua · Alcantarillado · Saneamiento · Resiliencia</small></span></a><button class="nav-toggle" type="button" aria-expanded="false" aria-controls="primary-nav"><span></span><span></span><span></span><b>Menú</b></button><nav class="primary-nav" id="primary-nav"><a class="nav-home<?= $current === 'index.php' ? ' is-active' : '' ?>" href="/index.php">Inicio</a>
<div class="nav-group<?= navActive($servicePages,$current) ?>"><button class="nav-group-button" type="button">Servicios <span>⌄</span></button><div class="nav-dropdown"><a href="/agua-potable.php"><b>Agua potable</b><small>Captación, bombeo y distribución</small></a><a href="/alcantarillado.php"><b>Alcantarillado</b><small>Recolección y conducción</small></a><a href="/saneamiento.php"><b>Saneamiento</b><small>Tratamiento y reúso</small></a></div></div>
<div class="nav-group<?= navActive($citizenPages,$current) ?>"><button class="nav-group-button" type="button">Ciudadanía <span>⌄</span></button><div class="nav-dropdown"><a href="/pago.php"><b>Pago y facturación</b><small>Recibo digital y pago en línea</small></a><a href="/tramites.php"><b>Trámites</b><small>Solicitudes y servicios</small></a><a href="/reportes.php"><b>Reportes</b><small>Fugas y atención 24/7</small></a><a href="/cultura-agua.php"><b>Cultura del Agua</b><small>Ahorro, prevención y calculadora</small></a><a href="/afectaciones.php"><b>Mapa de afectaciones</b><small>Cortes, obras y mantenimientos</small></a><?php if($isLogged): ?><a href="/mis-servicios.php"><b>Mis servicios</b><small>Cuentas y medidores vinculados</small></a><a href="/lectura-medidor.php"><b>Lectura del medidor</b><small>Captura y seguimiento</small></a><a href="/panel.php"><b>Mi portal</b><small>Resumen de tu cuenta</small></a><a href="/facturacion.php"><b>Mi facturación</b><small>Recibos, consumo y pagos</small></a><?php endif; ?></div></div>
<div class="nav-group<?= navActive($institutionPages,$current) ?>"><button class="nav-group-button" type="button">Institucional <span>⌄</span></button><div class="nav-dropdown nav-dropdown-wide"><div><span class="nav-kicker">Organización</span><a href="/quienes-somos.php"><b>Quiénes somos</b><small>Misión y trayectoria</small></a><a href="/organizacion.php"><b>Organización</b><small>Estructura y responsabilidades</small></a><a href="/directorio.php"><b>Directorio</b><small>Equipo directivo</small></a></div><div><span class="nav-kicker">Información</span><a href="/infraestructura.php"><b>Infraestructura estratégica</b><small>Activos y operación</small></a><a href="/observatorio.php"><b>Observatorio Hídrico</b><small>Indicadores y datos abiertos</small></a><a href="/prensa.php"><b>Sala de prensa</b><small>Avisos y modernización</small></a><a href="/redes-sociales.php"><b>Conversación digital</b><small>Redes, servicio y escucha social</small></a><a href="/transparencia.php"><b>Transparencia</b><small>Contratos e información pública</small></a><a href="/informes.php"><b>Informes anuales</b><small>Archivo histórico 1978–2026</small></a></div></div></div>
<?php if($__all_flags): ?><a class="nav-system-tab<?= $current==='system.php'?' is-active':'' ?>" href="/system.php">// SYSTEM //</a><?php endif; ?>
<div class="nav-group<?= navActive(['proveedores.php','contrataciones.php','licitaciones.php','licitacion.php','validar-referencia.php'],$current) ?>"><button class="nav-group-button" type="button">Contrataciones <span>⌄</span></button><div class="nav-dropdown"><a href="/proveedores.php"><b>Padrón de proveedores</b><small>219 proveedores registrados</small></a><a href="/contrataciones.php"><b>Contratos</b><small>Consulta objeto, monto y origen</small></a><a href="/licitaciones.php"><b>Licitaciones y obra</b><small>Procedimientos, bases y calendarios</small></a></div></div></nav>
<?php if($isLogged): ?><a class="account-button" href="/panel.php"><span class="account-avatar"><?= htmlspecialchars(mb_substr($_SESSION['user']['nombre'] ?? 'U',0,1)) ?></span><span><small>Sesión activa</small><b>Mi portal</b></span></a><?php else: ?><a class="account-button account-login" href="/login.php"><span class="account-icon">↗</span><span><small>Portal ciudadano</small><b>Acceso</b></span></a><?php endif; ?></div></header>
<?php if($current !== 'index.php'): ?><div class="breadcrumb-bar"><div class="wrap breadcrumb"><a href="/index.php">Inicio</a><span>›</span><strong><?= htmlspecialchars($pageTitle) ?></strong></div></div><?php endif; ?><main id="contenido">