<?php require_once __DIR__.'/includes/config.php'; require_auth(); log_page_view('activity.php','Bitácora');
$source=trim((string)($_GET['source']??''));
$sql="SELECT * FROM lab_activity WHERE attempt_id=?"; $params=[current_attempt_id()];
if($source!==''){ $sql.=" AND source_system=?"; $params[]=$source; }
$sql.=" ORDER BY created_at DESC,id DESC"; $q=db()->prepare($sql);$q->execute($params);$rows=$q->fetchAll();
$q=db()->prepare("SELECT source_system,COUNT(*) total FROM lab_activity WHERE attempt_id=? GROUP BY source_system ORDER BY total DESC");$q->execute([current_attempt_id()]);$sources=$q->fetchAll();
$pageTitle='Bitácora'; include __DIR__.'/includes/header.php'; ?>
<section class="hero compact"><div><p class="eyebrow">Registro integral</p><h1>Bitácora de actividad</h1><p>Registro forense del intento: navegación en INTERAFAS y Pulso Metropolitano, acciones OT, validaciones, pistas, recuperación, exportaciones y cierre.</p></div><div class="phase-card"><span>Registros</span><strong><?=count($rows)?></strong><small>Intento #<?=current_attempt_id()?></small></div></section>
<section class="panel"><div class="panel-head"><div><h2>Actividad del estudiante</h2><div class="export-links"><a class="secondary linkbtn" href="activity.php">Todo</a><?php foreach($sources as $src):?><a class="secondary linkbtn" href="?source=<?=urlencode($src['source_system'])?>"><?=h($src['source_system'])?> (<?=(int)$src['total']?>)</a><?php endforeach;?></div></div><div class="export-links"><a class="secondary linkbtn" href="export.php?format=csv">CSV</a><a class="secondary linkbtn" href="export.php?format=json">JSON</a></div></div><?php if(!$rows):?><div class="empty">Aún no hay actividad.</div><?php else:?><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Evento</th><th>Origen</th><th>Detalle</th><th>IP</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=h($r['created_at'])?></td><td><b><?=h($r['action_label'])?></b><small class="block"><?=h($r['action_code'])?></small></td><td><b><?=h($r['source_system']??'auditor')?></b><small class="block"><?=h($r['severity']??'info')?></small></td><td><?=h($r['detail']??'—')?><?php if($r['metadata_json']):?><small class="block mono"><?=h($r['metadata_json'])?></small><?php endif;?></td><td><?=h($r['ip_address']??'—')?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php include __DIR__.'/includes/footer.php'; ?>
