<?php
require_once __DIR__.'/includes/config.php'; require_auth(); log_page_view('flags.php','Banderas');
$msg=''; $err=''; $hintMsg=''; $selectedHintFlag=max(1,min(20,(int)($_POST['hint_flag']??$_GET['hint_flag']??1)));
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!attempt_is_active()){$err='El laboratorio ya fue finalizado. La captura de banderas y solicitud de pistas está cerrada.';}
 else{
  verify_csrf(); $action=(string)($_POST['action']??'flag');
  if($action==='hint'){
    $flagNo=$selectedHintFlag;
    $q=db()->prepare("SELECT h.hint_order,h.hint_text FROM flag_hints h WHERE h.flag_number=? AND NOT EXISTS (SELECT 1 FROM lab_hint_usage u WHERE u.attempt_id=? AND u.flag_number=h.flag_number AND u.hint_order=h.hint_order) ORDER BY h.hint_order LIMIT 1");
    $q->execute([$flagNo,current_attempt_id()]); $hint=$q->fetch();
    if(!$hint){$hintMsg='No quedan más pistas configuradas para el reto '.sprintf('%02d',$flagNo).'.';}
    else{
      $i=db()->prepare("INSERT INTO lab_hint_usage(attempt_id,student_id,flag_number,hint_order) VALUES(?,?,?,?)");
      $i->execute([current_attempt_id(),current_student_id(),$flagNo,(int)$hint['hint_order']]);
      log_activity('HINT_REQUESTED','Pista consultada','Reto '.sprintf('%02d',$flagNo).' · pista '.(int)$hint['hint_order'],['flag_number'=>$flagNo,'hint_order'=>(int)$hint['hint_order']],'auditor','notice');
      $hintMsg='Reto '.sprintf('%02d',$flagNo).' · Pista '.(int)$hint['hint_order'].': '.$hint['hint_text'];
    }
  } else {
    $flag=trim((string)($_POST['flag']??'')); $note=trim((string)($_POST['note']??''));
    $q=db()->prepare("SELECT * FROM flag_catalog WHERE flag_value=?"); $q->execute([$flag]); $cat=$q->fetch();
    if(!$cat){$err='La bandera no es válida.'; log_activity('FLAG_REJECTED','Intento de bandera rechazado','Se intentó registrar una bandera que no pertenece al catálogo.',['submitted'=>$flag]);}
    else{
      $dup=db()->prepare("SELECT id,created_at FROM flag_submissions WHERE attempt_id=? AND flag_number=? AND status='accepted' LIMIT 1"); $dup->execute([current_attempt_id(),$cat['flag_number']]); $d=$dup->fetch();
      if($d){$err='La bandera '.sprintf('%02d',$cat['flag_number']).' ya fue registrada el '.$d['created_at'].'.'; log_activity('FLAG_DUPLICATE','Bandera duplicada','Se volvió a enviar una bandera ya acreditada.',['flag_number'=>(int)$cat['flag_number']]);}
      else{
       db()->beginTransaction();
       try{
         $ins=db()->prepare("INSERT INTO flag_submissions(attempt_id,flag_number,flag_value,status,note,submitted_by) VALUES(?,?,?,'accepted',?,?)");
         $student=current_student(); $ins->execute([current_attempt_id(),$cat['flag_number'],$flag,$note,$student['matricula']??'']);
         $autoCheck=db()->prepare("INSERT INTO lab_checklist_state(attempt_id,student_id,flag_number,item_index,is_checked,updated_at) VALUES(?,?,?,?,1,NOW()) ON DUPLICATE KEY UPDATE is_checked=1,updated_at=NOW()");
         foreach([0,1,2] as $autoItem){$autoCheck->execute([current_attempt_id(),current_student_id(),(int)$cat['flag_number'],$autoItem]);}
         $ev=db()->prepare("INSERT IGNORE INTO scenario_events(attempt_id,event_code,flag_number,source,detail) VALUES(?,?,?,?,?)");
         $ev->execute([current_attempt_id(),'FLAG_'.sprintf('%02d',$cat['flag_number']),(int)$cat['flag_number'],'auditor-portal','Bandera validada desde Portal del Auditor']);
         $allQ=db()->prepare("SELECT COUNT(DISTINCT flag_number) FROM flag_submissions WHERE attempt_id=? AND status='accepted'"); $allQ->execute([current_attempt_id()]);
         if((int)$allQ->fetchColumn()>=20){ $ev->execute([current_attempt_id(),'ALL_FLAGS',null,'auditor-portal','Las 20 banderas del laboratorio fueron acreditadas']); }
         db()->commit();
         log_activity('FLAG_ACCEPTED','Bandera acreditada','Bandera '.sprintf('%02d',$cat['flag_number']).' registrada correctamente.',['flag_number'=>(int)$cat['flag_number'],'code_name'=>$cat['code_name'],'difficulty'=>(int)$cat['difficulty'],'weight'=>(int)$cat['weight']]);
         $msg='Bandera '.sprintf('%02d',$cat['flag_number']).' validada. El escenario fue actualizado automáticamente.';
       }catch(Throwable $e){if(db()->inTransaction())db()->rollBack();$err='No fue posible registrar la bandera.';log_activity('FLAG_ERROR','Error al registrar bandera',$e->getMessage());}
      }
    }
  }
 }
}
$q=db()->prepare("SELECT c.*,s.created_at AS obtained_at,s.note FROM flag_submissions s JOIN flag_catalog c ON c.flag_number=s.flag_number WHERE s.attempt_id=? AND s.status='accepted' ORDER BY s.created_at,c.flag_number");$q->execute([current_attempt_id()]);$obtained=$q->fetchAll();
$q=db()->prepare("SELECT u.flag_number,u.hint_order,h.hint_text,u.created_at FROM lab_hint_usage u JOIN flag_hints h ON h.flag_number=u.flag_number AND h.hint_order=u.hint_order WHERE u.attempt_id=? ORDER BY u.created_at DESC,u.id DESC");$q->execute([current_attempt_id()]);$usedHints=$q->fetchAll(); $usedHintsByFlag=[]; foreach($usedHints as $uh){$usedHintsByFlag[(int)$uh['flag_number']][]=$uh;}
$q=db()->prepare("SELECT flag_number,item_index,is_checked FROM lab_checklist_state WHERE attempt_id=?");$q->execute([current_attempt_id()]);$checkRows=$q->fetchAll(); $checkState=[]; foreach($checkRows as $cr){$checkState[(int)$cr['flag_number']][(int)$cr['item_index']]=(int)$cr['is_checked']===1;}

$challengeChecklist=[
1=>['Parte de una función pública normal del portal y observa cómo están organizados sus recursos.','Comprueba si el servidor permite explorar el directorio que contiene recursos legítimos.','Distingue los documentos esperados de cualquier artefacto residual de operación o despliegue.'],
2=>['Inspecciona lo que el navegador recibe además de lo que muestra.','Busca referencias, rutas o comentarios que aporten contexto adicional.','Conserva evidencia del recurso del lado cliente donde aparezca el hallazgo.'],
3=>['Compara objetos similares dentro de una misma función.','Verifica si cambiar un identificador modifica el recurso consultado.','Confirma si el servidor valida que el objeto pertenece al usuario autenticado.'],
4=>['Revisa rastros de versiones anteriores y archivos residuales.','Comprueba si copias o respaldos quedaron accesibles.','Explica qué información adicional aporta el artefacto encontrado.'],
5=>['Identifica una función del portal que genere una descarga dinámica y observa qué solicitud realiza el navegador.','Determina qué parámetro controla el contenido solicitado y prueba una entrada no contemplada por la interfaz.','Compara la respuesta del servidor y registra cualquier detalle técnico que no debería exponerse al usuario final.'],
6=>['Accede con una cuenta ciudadana a una función marcada para personal autorizado y registra la respuesta del servidor.','Inspecciona la solicitud HTTP y sus cookies para identificar si algún dato controlado por el cliente parece representar el rol o privilegio.','Modifica únicamente ese dato, repite la solicitud y comprueba si el servidor permite ejecutar una operación administrativa con la misma sesión ciudadana.'],
7=>['Confirma si la respuesta de la aplicación puede controlarse mediante una condición SQL verdadera o falsa.','Utiliza el canal booleano para identificar la base de datos y enumerar su estructura.','Localiza información de validación relevante e infiere su contenido sin depender de errores SQL ni de resultados mostrados directamente.'],
8=>['Identifica un campo de entrada cuyo contenido se almacene y vuelva a mostrarse posteriormente.','Comprueba si la salida se inserta en contexto HTML sin codificación y prueba una ejecución JavaScript inocua dentro del laboratorio.','Inspecciona el HTML de la vista vulnerable, localiza el mecanismo de acreditación disponible y demuéstralo mediante una petición HTTP originada por tu JavaScript almacenado.'],
9=>['Identifica un parámetro utilizado por una función legítima para seleccionar un archivo dentro de un directorio previsto.','Comprueba si secuencias de navegación de directorios permiten salir de la ubicación esperada y valida el comportamiento con archivos estándar y previsibles del sistema operativo del laboratorio.','Documenta la profundidad necesaria, la petición utilizada y la evidencia de que el servidor entregó un archivo ajeno al directorio autorizado.'],
10=>['Registra el identificador de sesión que el portal entrega antes de autenticarte.','Autentícate y compara si ese identificador cambia al pasar de una sesión anónima a una sesión autenticada.','Si permanece igual, reutiliza exclusivamente ese identificador previo desde un segundo cliente y comprueba si una página protegida reconoce la sesión sin solicitar credenciales.'],
11=>['Navega por Mi portal y observa las solicitudes HTTP que el frontend genera en segundo plano.','Inspecciona las respuestas JSON completas y busca relaciones o rutas que la interfaz no represente visualmente.','Solicita el recurso no documentado encontrado y documenta método, autenticación, contenido y evidencia de que forma parte de la superficie real de la aplicación.'],
12=>['Retoma el endpoint histórico descubierto en el reto anterior e identifica qué parámetro selecciona la cuenta de servicio consultada.','Mantén la misma sesión autenticada y modifica únicamente el identificador del objeto; compara la respuesta de tu cuenta con la de otro identificador válido del laboratorio.','Determina si el servidor comprueba la propiedad del objeto y conserva como evidencia la petición, el código HTTP y sólo los campos mínimos necesarios para demostrar el acceso cruzado.'],
13=>['Selecciona un recibo pendiente y documenta la regla visible del flujo: el importe se fija al saldo total y la operación debe liquidar el recibo completo.','Intercepta o edita la solicitud de confirmación manteniendo la misma sesión, cuenta y factura; modifica únicamente el valor monto por un importe positivo inferior al saldo esperado.','Compara el pago registrado con el estado final del recibo y del saldo de la cuenta. Determina si el servidor volvió a validar el importe autorizado antes de dar la operación por liquidada.'],
14=>['Desde Contrataciones utiliza la función pública Validar vínculo de un contrato y registra los identificadores de contrato y proveedor que la aplicación envía.','Mantén el mismo contrato y cambia únicamente provider_id por el ID de otro proveedor vigente que puedas observar en el padrón público.','Compara el resultado legítimo con el modificado y determina si el servicio valida la relación entre ambas entidades o sólo la existencia y vigencia de cada registro por separado.'],
15=>['Visita Infraestructura estratégica y observa las solicitudes que la página genera para mostrar el estado de integración del Centro de Operaciones.','Inspecciona la respuesta completa del servicio de estado e identifica metadatos de diagnóstico que la interfaz no muestra: componentes, fronteras de confianza, segmentos de red, rutas de aplicación o nombres de servicios internos.','Construye un mapa mínimo de dependencias desde el portal web hasta el puente operacional e incluye cualquier zona o CIDR expuesto. Comprueba únicamente la ruta de aplicación publicada y registra su respuesta restringida; los nombres marcados como internos no son destinos accesibles desde el navegador.'],
16=>['Retoma el gateway restringido y el segmento operacional documentados en el reto anterior. Registra qué política declara el servidor cuando responde HTTP 403.','Investiga cómo los proxies HTTP comunican la dirección original del cliente y prueba si el gateway confía en un encabezado controlable por la petición para decidir que el origen pertenece a ese segmento.','Si logras cruzar la frontera, conserva como evidencia la solicitud modificada, los encabezados de validación y la puerta de entrada operacional revelada por el gateway. En este reto todavía no debes obtener variables de proceso ni ejecutar acciones de control.'],
17=>['Retoma la única ruta operacional revelada por el gateway y confirma que conduce al acceso legítimo del Centro de Operaciones.','Inspecciona los recursos que carga esa página e identifica el cliente JavaScript compartido por la aplicación. A partir de él determina qué endpoint utiliza el HMI para refrescar telemetría.','Compara el control de sesión de la consola principal con el del servicio de telemetría y documenta únicamente las variables necesarias para demostrar la exposición. No ejecutes acciones de control ni accedas todavía al mantenimiento de firmware.'],
18=>['Retoma el estado de actualización visible en la telemetría y revisa el cliente web compartido para identificar el servicio que consulta el HMI cuando necesita detalles de firmware. Desde ahí sigue únicamente las rutas declaradas hasta el manifiesto.','Analiza los metadatos release y support del manifiesto. Identifica una posible identidad de mantenimiento y clasifica el verificador heredado: algoritmo probable, longitud, codificación y si contiene salt. Documenta qué evidencia respalda tu clasificación.','Trabaja el verificador exclusivamente de forma offline. Conserva el hash original, normalízalo si contiene un prefijo descriptivo y prueba primero un ataque de diccionario; después utiliza reglas o candidatos construidos con el contexto del manifiesto. Registra herramienta, modo/formato, wordlist o reglas empleadas y el candidato recuperado.','Valida el candidato recalculando el digest antes de utilizarlo y prueba la identidad deducida únicamente contra el acceso operacional del laboratorio. Confirma que el rol recuperado permite mantenimiento pero no control del HMI ni acciones sobre P-101.','Obtén el paquete aprobado y distingue integridad de autenticidad. Modifica únicamente el payload, recalcula SHA-256 y comprueba si el instalador acepta contenido no aprobado sin verificar una firma del emisor. Conserva paquete original, variante, hashes y respuesta; no alteres variables de proceso.'],
19=>['Relaciona hallazgos previos en lugar de buscar una vulnerabilidad aislada.','Construye la secuencia de pasos que conecta web, arquitectura y entorno operacional.','Conserva evidencia de cada salto de la cadena.'],
20=>['Define primero cuál es el impacto operacional simulado que debes demostrar.','Comprueba qué prerrequisitos de la cadena anterior habilitan la acción final.','Registra estado antes/después, alarmas y evidencia de recuperación del simulador.']
];

$challengeResources=[
1=>[
 ['type'=>'MDN','title'=>'robots.txt configuration','url'=>'https://developer.mozilla.org/en-US/docs/Web/Security/Practical_implementation_guides/Robots_txt','desc'=>'Qué es robots.txt, dónde se publica y para qué sirve realmente dentro de un sitio web.'],
 ['type'=>'RFC 9309','title'=>'Robots Exclusion Protocol','url'=>'https://www.rfc-editor.org/rfc/rfc9309.html','desc'=>'Estándar del protocolo. Su sección de seguridad explica por qué robots.txt no sustituye un control de acceso.'],
 ['type'=>'OWASP','title'=>'Old Backup and Unreferenced Files','url'=>'https://owasp.github.io/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management/04-Review_Old_Backup_and_Unreferenced_Files_for_Sensitive_Information','desc'=>'Metodología para localizar archivos residuales y directorios no enlazados; incluye robots.txt como fuente de pistas.']
],
2=>[
 ['type'=>'OWASP','title'=>'Review Web Page Content for Information Leakage','url'=>'https://wstg.owasp.org/latest/4-Web_Application_Security_Testing/01-Information_Gathering/05-Review_Web_Page_Content_for_Information_Leakage/','desc'=>'Revisión de HTML, JavaScript y recursos recibidos por el navegador para detectar información expuesta.'],
 ['type'=>'MDN','title'=>'Source maps y recursos del frontend','url'=>'https://developer.mozilla.org/en-US/docs/Glossary/Source_map','desc'=>'Concepto de artefactos auxiliares del frontend y por qué pueden revelar detalles que no son visibles en la interfaz.'],
 ['type'=>'PortSwigger','title'=>'Information disclosure','url'=>'https://portswigger.net/web-security/information-disclosure','desc'=>'Casos prácticos de información sensible expuesta por configuración, archivos o código del cliente.']
],
3=>[
 ['type'=>'OWASP','title'=>'Insecure Direct Object References (IDOR)','url'=>'https://wstg.owasp.org/latest/4-Web_Application_Security_Testing/05-Authorization/04-Insecure_Direct_Object_References/','desc'=>'Guía de pruebas para detectar referencias directas a objetos sin una comprobación adecuada de autorización.'],
 ['type'=>'OWASP Cheat Sheet','title'=>'IDOR Prevention Cheat Sheet','url'=>'https://cheatsheetseries.owasp.org/cheatsheets/Insecure_Direct_Object_Reference_Prevention_Cheat_Sheet.html','desc'=>'Explica por qué cambiar identificadores puede permitir consultar objetos de otro usuario y cómo debería prevenirse.'],
 ['type'=>'PortSwigger','title'=>'Insecure direct object references (IDOR)','url'=>'https://portswigger.net/web-security/access-control/idor','desc'=>'Explicación práctica de IDOR y escalamiento horizontal mediante identificadores controlados por el usuario.']
],
4=>[
 ['type'=>'OWASP','title'=>'Old Backup and Unreferenced Files','url'=>'https://wstg.owasp.org/latest/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management/04-Review_Old_Backup_and_Unreferenced_Files_for_Sensitive_Information/','desc'=>'Cómo localizar copias .bak, .old, archivos terminados en ~ y otros artefactos residuales que el servidor puede exponer.'],
 ['type'=>'PortSwigger','title'=>'Source code disclosure via backup files','url'=>'https://portswigger.net/web-security/information-disclosure/exploiting','desc'=>'Explica por qué una copia con otra extensión puede devolver el código fuente en lugar de ejecutarlo.'],
 ['type'=>'PortSwigger KB','title'=>'Backup file','url'=>'https://portswigger.net/kb/issues/006000d8_backup-file','desc'=>'Referencia específica sobre riesgos de archivos de respaldo expuestos dentro del web root.']
],
5=>[
 ['type'=>'OWASP','title'=>'Testing for Improper Error Handling','url'=>'https://wstg.owasp.org/v4.2/4-Web_Application_Security_Testing/08-Testing_for_Error_Handling/01-Testing_For_Improper_Error_Handling/','desc'=>'Metodología para enviar entradas inesperadas y analizar si la aplicación revela excepciones, rutas, componentes internos o diferencias útiles en sus respuestas.'],
 ['type'=>'PHP','title'=>'match expression','url'=>'https://www.php.net/manual/en/control-structures.match.php','desc'=>'Documentación oficial de PHP sobre match. Explica que una entrada no contemplada por ningún brazo provoca un UnhandledMatchError.'],
 ['type'=>'PHP','title'=>'UnhandledMatchError','url'=>'https://www.php.net/manual/en/class.unhandledmatcherror.php','desc'=>'Referencia oficial de la excepción real que puede generarse cuando un valor no está contemplado en una expresión match.'],
 ['type'=>'PortSwigger','title'=>'Information disclosure in error messages','url'=>'https://portswigger.net/web-security/information-disclosure/exploiting/lab-infoleak-in-error-messages','desc'=>'Laboratorio centrado en cómo los mensajes de error verbosos pueden revelar información técnica sensible.'],
 ['type'=>'PortSwigger','title'=>'Exploiting information disclosure','url'=>'https://portswigger.net/web-security/information-disclosure/exploiting','desc'=>'Explica cómo los errores verbosos y las diferencias entre respuestas pueden utilizarse para obtener información sobre la aplicación.']
],
6=>[
 ['type'=>'OWASP','title'=>'Testing for Privilege Escalation','url'=>'https://wstg.owasp.org/v4.2/4-Web_Application_Security_Testing/05-Authorization_Testing/03-Testing_for_Privilege_Escalation/','desc'=>'Guía para comprobar escalamiento vertical: una cuenta de menor privilegio obtiene acceso a funciones o recursos reservados a perfiles superiores.'],
 ['type'=>'OWASP','title'=>'Testing for Bypassing Authorization Schema','url'=>'https://wstg.owasp.org/v4.2/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema/','desc'=>'Metodología para probar si el servidor aplica realmente el esquema de autorización definido para cada rol o privilegio.'],
 ['type'=>'PortSwigger','title'=>'User role controlled by request parameter','url'=>'https://portswigger.net/web-security/access-control/lab-user-role-controlled-by-request-parameter','desc'=>'Laboratorio directamente relacionado: el rol administrativo depende de un dato controlado por el cliente y puede manipularse para obtener acceso privilegiado.'],
 ['type'=>'PortSwigger','title'=>'Testing for parameter-based access control','url'=>'https://portswigger.net/burp/documentation/desktop/testing-workflow/vulnerabilities/access-controls/param-based-access-control','desc'=>'Procedimiento práctico para interceptar solicitudes, identificar datos de autorización enviados por el cliente y probar su modificación con Burp Suite.'],
 ['type'=>'OWASP API','title'=>'Broken Function Level Authorization','url'=>'https://api-security.owasp.org/editions/2023/en/0xa5-broken-function-level-authorization/','desc'=>'Describe fallos donde usuarios normales pueden ejecutar funciones administrativas o privilegiadas por controles de autorización insuficientes.']
],
7=>[
 ['type'=>'PortSwigger','title'=>'Blind SQL injection','url'=>'https://portswigger.net/web-security/sql-injection/blind','desc'=>'Explica cómo inferir información cuando la aplicación solo permite distinguir entre condiciones verdaderas y falsas.'],
 ['type'=>'PortSwigger','title'=>'Blind SQL injection with conditional responses','url'=>'https://portswigger.net/web-security/sql-injection/blind/lab-conditional-responses','desc'=>'Ejemplo práctico de inferencia carácter por carácter mediante respuestas condicionales.'],
 ['type'=>'OWASP','title'=>'Testing for SQL Injection','url'=>'https://wstg.owasp.org/v4.2/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05-Testing_for_SQL_Injection/','desc'=>'Metodología para identificar y validar puntos de entrada SQL.'],
 ['type'=>'OWASP','title'=>'Testing for MySQL','url'=>'https://wstg.owasp.org/v4.2/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05.2-Testing_for_MySQL/','desc'=>'Particularidades de MySQL/MariaDB relevantes para consultas de inferencia y enumeración.'],
 ['type'=>'MariaDB','title'=>'SUBSTRING','url'=>'https://mariadb.com/docs/server/reference/sql-functions/string-functions/substring','desc'=>'Documentación de la función usada para comprobar posiciones individuales dentro de cadenas.'],
 ['type'=>'MariaDB','title'=>'Information Schema','url'=>'https://mariadb.com/docs/server/reference/system-tables/information-schema','desc'=>'Catálogo de metadatos para descubrir esquemas, tablas y columnas.'],
 ['type'=>'MariaDB','title'=>'Information Schema TABLES','url'=>'https://mariadb.com/docs/server/reference/system-tables/information-schema/information-schema-tables/information-schema-tables-table','desc'=>'Referencia para enumerar tablas dentro de un esquema.'],
 ['type'=>'MariaDB','title'=>'Information Schema COLUMNS','url'=>'https://mariadb.com/docs/server/reference/system-tables/information-schema/information-schema-tables/information-schema-columns-table','desc'=>'Referencia para enumerar las columnas de una tabla encontrada.'],
 ['type'=>'MariaDB','title'=>'SELECT','url'=>'https://mariadb.com/docs/server/reference/sql-statements/data-manipulation/selecting-data/select','desc'=>'Sintaxis de SELECT para consultar valores de columnas como tokens de validación una vez localizada la estructura.'],
 ['type'=>'MariaDB','title'=>'WHERE','url'=>'https://mariadb.com/docs/server/reference/sql-statements/data-manipulation/selecting-data/where','desc'=>'Uso de condiciones para filtrar registros por claves o contextos concretos dentro de una tabla.'],
 ['type'=>'MariaDB','title'=>'Identifier Names','url'=>'https://mariadb.com/docs/server/reference/sql-structure/sql-language-structure/identifier-names','desc'=>'Cómo interpretar nombres de tablas y columnas como portal_validation_meta, verification_token o context_key cuando aparezcan durante la enumeración.'],
 ['type'=>'PortSwigger','title'=>'SQL injection cheat sheet','url'=>'https://portswigger.net/web-security/sql-injection/cheat-sheet','desc'=>'Referencia práctica de sintaxis para condiciones, subconsultas, comentarios y metadatos.']
],
8=>[
 ['type'=>'OWASP','title'=>'Testing for Stored Cross Site Scripting','url'=>'https://wstg.owasp.org/v4.2/4-Web_Application_Security_Testing/07-Input_Validation_Testing/02-Testing_for_Stored_Cross_Site_Scripting/','desc'=>'Metodología específica para identificar entradas persistentes que se almacenan y posteriormente se renderizan de forma insegura.'],
 ['type'=>'PortSwigger','title'=>'Stored cross-site scripting','url'=>'https://portswigger.net/web-security/cross-site-scripting/stored','desc'=>'Explica cómo aparece el XSS persistente cuando datos no confiables se guardan y se incluyen después en respuestas HTML sin tratamiento seguro.'],
 ['type'=>'PortSwigger','title'=>'Testing for stored XSS with Burp Suite','url'=>'https://portswigger.net/burp/documentation/desktop/testing-workflow/vulnerabilities/input-validation/xss/testing-for-stored-xss','desc'=>'Flujo práctico para localizar el punto de almacenamiento, encontrar la vista donde reaparece la entrada y comprobar ejecución.'],
 ['type'=>'OWASP','title'=>'XSS Prevention Cheat Sheet','url'=>'https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html','desc'=>'Explica por qué la codificación de salida debe depender del contexto y cómo evitar que datos almacenados sean interpretados como código.'],
 ['type'=>'MDN','title'=>'Document.querySelector()','url'=>'https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector','desc'=>'Permite localizar elementos del DOM mediante selectores CSS, útil para encontrar metadatos y otros elementos disponibles en la vista vulnerable.'],
 ['type'=>'MDN','title'=>'HTML meta element','url'=>'https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/meta','desc'=>'Explica cómo funciona el elemento meta y cómo puede contener información asociada a la página que después puede consultarse desde JavaScript.'],
 ['type'=>'MDN','title'=>'Fetch API','url'=>'https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch','desc'=>'Guía práctica para realizar peticiones HTTP desde JavaScript y procesar respuestas con fetch().'],
 ['type'=>'MDN','title'=>'const declaration','url'=>'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const','desc'=>'Explica el alcance de const y por qué una constante no puede volver a declararse en el mismo ámbito de la consola.'],
 ['type'=>'Chrome DevTools','title'=>'Inspect network activity','url'=>'https://developer.chrome.com/docs/devtools/network/','desc'=>'Permite observar las peticiones generadas por JavaScript, códigos HTTP, encabezados y contenido de las respuestas.']
],
9=>[
 ['type'=>'PortSwigger','title'=>'Path traversal','url'=>'https://portswigger.net/web-security/file-path-traversal','desc'=>'Explica cómo una aplicación que concatena un nombre de archivo con un directorio base puede permitir salir de esa ubicación mediante secuencias de traversal.'],
 ['type'=>'PortSwigger','title'=>'File path traversal, simple case','url'=>'https://portswigger.net/web-security/file-path-traversal/lab-simple','desc'=>'Laboratorio introductorio para comprender cómo modificar un parámetro de archivo y acceder a un recurso fuera del directorio previsto.'],
 ['type'=>'OWASP','title'=>'Testing Directory Traversal File Include','url'=>'https://wstg.owasp.org/v4.2/4-Web_Application_Security_Testing/07-Input_Validation_Testing/11.1-Testing_for_File_Inclusion/','desc'=>'Metodología para identificar parámetros de archivo, probar secuencias de traversal y documentar el acceso a recursos fuera de la ubicación esperada.'],
 ['type'=>'PHP','title'=>'Filesystem Functions','url'=>'https://www.php.net/manual/en/ref.filesystem.php','desc'=>'Referencia de funciones de archivo de PHP como is_file(), is_readable() y readfile(), útiles para comprender cómo una aplicación puede leer rutas construidas dinámicamente.'],
 ['type'=>'PHP','title'=>'realpath','url'=>'https://www.php.net/manual/en/function.realpath.php','desc'=>'Permite entender cómo debería normalizarse una ruta antes de comprobar que permanece dentro del directorio autorizado.']
],
10=>[
 ['type'=>'OWASP WSTG v4.2','title'=>'Testing for Session Fixation','url'=>'https://wstg.owasp.org/v4.2/4-Web_Application_Security_Testing/06-Session_Management_Testing/03-Testing_for_Session_Fixation/','desc'=>'Guía específica WSTG-SESS-03 para comprobar si el identificador de sesión se conserva antes y después de la autenticación y puede reutilizarse.'],
 ['type'=>'OWASP WSTG v4.2','title'=>'Testing for Session Management Schema','url'=>'https://wstg.owasp.org/v4.2/4-Web_Application_Security_Testing/06-Session_Management_Testing/01-Testing_for_Session_Management_Schema/','desc'=>'Contexto para analizar cómo la aplicación crea, transporta y valida sus identificadores de sesión.'],
 ['type'=>'OWASP Cheat Sheet','title'=>'Session Management Cheat Sheet','url'=>'https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html','desc'=>'Buenas prácticas para rotación de identificadores, cookies y transición entre estados de autenticación.']
],
11=>[
 ['type'=>'OWASP WSTG v4.2','title'=>'Identify Application Entry Points','url'=>'https://wstg.owasp.org/v4.2/4-Web_Application_Security_Testing/01-Information_Gathering/06-Identify_Application_Entry_Points/','desc'=>'WSTG-INFO-06: explica cómo identificar la superficie real de una aplicación registrando solicitudes, parámetros, encabezados y respuestas, no sólo enlaces visibles.'],
 ['type'=>'OWASP API Security','title'=>'API9:2023 Improper Inventory Management','url'=>'https://api-security.owasp.org/editions/2023/en/0xa9-improper-inventory-management/','desc'=>'Explica por qué versiones, hosts y endpoints API olvidados o no inventariados amplían la superficie de ataque aunque sigan funcionando correctamente.'],
 ['type'=>'PortSwigger','title'=>'API testing learning path','url'=>'https://portswigger.net/web-security/learning-paths/api-testing','desc'=>'Ruta práctica para descubrir APIs a partir del comportamiento normal del sitio, analizar documentación parcial y localizar funciones que el frontend no utiliza completamente.'],
 ['type'=>'PortSwigger Lab','title'=>'Finding and exploiting an unused API endpoint','url'=>'https://portswigger.net/web-security/api-testing/lab-exploiting-unused-api-endpoint','desc'=>'Ejercicio específico sobre cómo una aplicación puede revelar un endpoint API no utilizado directamente por su interfaz y cómo reconocerlo durante la navegación.'],
 ['type'=>'Firefox DevTools','title'=>'Network Monitor','url'=>'https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/index.html','desc'=>'Documentación del monitor de red de Firefox: permite revisar solicitudes XHR/fetch, encabezados y cuerpos de respuesta JSON generados mientras se usa el portal.']
],
12=>[
 ['type'=>'OWASP API Security','title'=>'API1:2023 Broken Object Level Authorization','url'=>'https://api-security.owasp.org/editions/2023/en/0xa1-broken-object-level-authorization/','desc'=>'Referencia principal de BOLA: cada endpoint que recibe un identificador de objeto debe comprobar que el usuario autenticado está autorizado para actuar sobre ese objeto.'],
 ['type'=>'OWASP WSTG','title'=>'API Broken Object Level Authorization','url'=>'https://wstg.owasp.org/latest/4-Web_Application_Security_Testing/12-API_Testing/02-API_Broken_Object_Level_Authorization/','desc'=>'WSTG-APIT-02: metodología específica para identificar parámetros de objeto y comparar el comportamiento al reutilizar la misma sesión con identificadores distintos.'],
 ['type'=>'OWASP WSTG','title'=>'Insecure Direct Object References','url'=>'https://wstg.owasp.org/latest/4-Web_Application_Security_Testing/05-Authorization/04-Insecure_Direct_Object_References/','desc'=>'Explica el patrón clásico de modificar referencias directas a registros y verificar si el servidor aplica autorización horizontal.'],
 ['type'=>'PortSwigger','title'=>'Testing for IDORs','url'=>'https://portswigger.net/burp/documentation/desktop/testing-workflow/vulnerabilities/access-controls/testing-for-idors','desc'=>'Flujo práctico para localizar identificadores controlados por el cliente, modificar sólo ese valor y comparar respuestas manteniendo el mismo contexto de autenticación.'],
 ['type'=>'PortSwigger','title'=>'Testing access controls','url'=>'https://portswigger.net/burp/documentation/desktop/testing-workflow/vulnerabilities/access-controls','desc'=>'Metodología general para comprobar controles de acceso horizontales y distinguir autenticación correcta de autorización insuficiente.']
],
13=>[
 ['type'=>'OWASP WSTG v4.2','title'=>'Introduction to Business Logic Testing','url'=>'https://wstg.owasp.org/v4.2/4-Web_Application_Security_Testing/10-Business_Logic_Testing/00-Introduction_to_Business_Logic/','desc'=>'Introduce las pruebas de reglas y estados de negocio: el objetivo es comprobar si la aplicación acepta secuencias o valores que contradicen las reglas funcionales previstas.'],
 ['type'=>'OWASP Cheat Sheet','title'=>'Business Logic Security','url'=>'https://cheatsheetseries.owasp.org/cheatsheets/Business_Logic_Security_Cheat_Sheet.html','desc'=>'Recomienda aplicar y validar reglas de negocio del lado servidor, especialmente en operaciones sensibles y cambios de estado.'],
 ['type'=>'OWASP Cheat Sheet','title'=>'Third Party Payment Gateway Integration','url'=>'https://cheatsheetseries.owasp.org/cheatsheets/Third_Party_Payment_Gateway_Integration_Cheat_Sheet.html','desc'=>'Guía específica para flujos de pago: importe, moneda, referencia y resultado deben verificarse de forma confiable antes de actualizar el estado interno de una operación.'],
 ['type'=>'PortSwigger','title'=>'Business logic vulnerabilities','url'=>'https://portswigger.net/web-security/logic-flaws','desc'=>'Explica cómo surgen fallos cuando el servidor confía en supuestos sobre el comportamiento normal del usuario o en controles aplicados sólo por el cliente.'],
 ['type'=>'PortSwigger Lab','title'=>'Excessive trust in client-side controls','url'=>'https://portswigger.net/web-security/logic-flaws/examples/lab-logic-flaws-excessive-trust-in-client-side-controls','desc'=>'Laboratorio directamente relacionado con la manipulación de un valor económico controlado por el cliente que el servidor no vuelve a validar.']
],
14=>[
 ['type'=>'OWASP Cheat Sheet','title'=>'Authorization Cheat Sheet','url'=>'https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html','desc'=>'Explica autorización contextual y basada en relaciones (ReBAC): no basta con tener un rol; debe comprobarse la relación concreta entre actor, acción y objeto en cada solicitud.'],
 ['type'=>'OWASP Cheat Sheet','title'=>'Business Logic Security','url'=>'https://cheatsheetseries.owasp.org/cheatsheets/Business_Logic_Security_Cheat_Sheet.html','desc'=>'Describe por qué el backend debe validar el significado de negocio de los identificadores y volver a comprobar propiedad, estado y relaciones en cada operación.'],
 ['type'=>'OWASP WSTG v4.2','title'=>'Testing for Insecure Direct Object References','url'=>'https://wstg.owasp.org/v4.2/4-Web_Application_Security_Testing/05-Authorization_Testing/04-Testing_for_Insecure_Direct_Object_References/','desc'=>'Metodología para identificar referencias a objetos controladas por el cliente y modificar parámetros individuales para comprobar operaciones sobre registros distintos.'],
 ['type'=>'PortSwigger','title'=>'Insecure direct object references (IDOR)','url'=>'https://portswigger.net/web-security/access-control/idor','desc'=>'Explica cómo parámetros controlados por el cliente pueden seleccionar directamente registros de base de datos cuando falta una validación contextual de acceso o relación.'],
 ['type'=>'OWASP Cheat Sheet','title'=>'Authorization Testing Automation','url'=>'https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Testing_Automation_Cheat_Sheet.html','desc'=>'Marco para modelar y comprobar matrices de autorización considerando sujetos, recursos, acciones y combinaciones que deberían ser rechazadas.']
],
15=>[
 ['type'=>'Firefox DevTools','title'=>'Network Monitor','url'=>'https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/index.html','desc'=>'Punto de partida práctico para el reto: muestra todas las solicitudes HTTP y XHR/fetch que genera una página mientras navegas por ella.'],
 ['type'=>'Firefox DevTools','title'=>'Network request details','url'=>'https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/request_details/','desc'=>'Explica cómo revisar Headers y Response de una solicitud. Es especialmente útil para inspeccionar el JSON completo que la interfaz resume u oculta.'],
 ['type'=>'OWASP WSTG v4.2','title'=>'Review Web Page Content for Information Leakage','url'=>'https://wstg.owasp.org/v4.2/4-Web_Application_Security_Testing/01-Information_Gathering/05-Review_Webpage_Content_for_Information_Leakage/','desc'=>'Metodología para localizar información técnica expuesta en HTML, JavaScript y recursos auxiliares, incluyendo rutas, nombres internos y detalles de configuración.'],
 ['type'=>'OWASP WSTG v4.2','title'=>'Identify Application Entry Points','url'=>'https://wstg.owasp.org/v4.2/4-Web_Application_Security_Testing/01-Information_Gathering/06-Identify_Application_Entry_Points/','desc'=>'Ayuda a registrar endpoints, respuestas y parámetros para transformar hallazgos aislados en un mapa de la superficie real de la aplicación.'],
 ['type'=>'Docker Docs','title'=>'Networking in Compose','url'=>'https://docs.docker.com/compose/how-tos/networking/','desc'=>'Explica que los servicios de Compose pueden resolverse entre contenedores por nombre dentro de su red. Ayuda a interpretar un hostname interno como ot-sim sin asumir que es accesible desde el navegador del host.'],
 ['type'=>'Docker Docs','title'=>'Publishing and exposing ports','url'=>'https://docs.docker.com/get-started/docker-concepts/running-containers/publishing-ports/','desc'=>'Aclara la diferencia entre un puerto disponible dentro de la red de contenedores y un puerto publicado hacia el host. Útil para distinguir servicio interno de ruta web alcanzable.'],
 ['type'=>'PortSwigger','title'=>'Information disclosure','url'=>'https://portswigger.net/web-security/information-disclosure','desc'=>'Explica por qué nombres de host, rutas internas y otros metadatos técnicos reducen la incertidumbre de un atacante y pueden habilitar etapas posteriores.']
],
16=>[
 ['type'=>'Firefox DevTools','title'=>'Network request details · Edit and Resend','url'=>'https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/request_details/','desc'=>'Guía práctica para seleccionar la petición del gateway, revisar sus encabezados y utilizar Edit and Resend para añadir o modificar headers sin salir del navegador.'],
 ['type'=>'MDN','title'=>'¿Qué es X-Forwarded-For?','url'=>'https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/X-Forwarded-For','desc'=>'X-Forwarded-For es un encabezado HTTP utilizado por proxies y balanceadores para comunicar al servidor la dirección IP original del cliente. Puede contener una cadena de direcciones cuando existen varios intermediarios. Su valor no demuestra por sí mismo el origen real de la petición: si el servidor acepta directamente un X-Forwarded-For enviado por el cliente, ese dato puede ser falsificado. Sólo debe utilizarse para decisiones de seguridad cuando la aplicación conoce y confía en los proxies que lo agregan o reescriben.'],
 ['type'=>'IETF','title'=>'RFC 1918 · Address Allocation for Private Internets','url'=>'https://datatracker.ietf.org/doc/html/rfc1918','desc'=>'Referencia sobre rangos IPv4 privados. Ayuda a comprender por qué una organización puede reservar un segmento como 10.40.20.0/24 para una zona operacional y por qué pertenecer a ese rango no debería demostrarse únicamente con un encabezado declarado por el cliente.'],
 ['type'=>'OWASP WSTG','title'=>'Bypassing Authorization Schema','url'=>'https://wstg.owasp.org/latest/4-Web_Application_Security_Testing/05-Authorization/02-Bypassing_Authorization_Schema/','desc'=>'Referencia central del reto: OWASP incluye encabezados de proxy como X-Forwarded-For entre los elementos que deben probarse cuando una función está restringida por red, origen o esquema de autorización.'],
 ['type'=>'OWASP','title'=>'IP Spoofing via HTTP Headers','url'=>'https://community.owasp.org/pages/attacks/ip_spoofing_via_http_headers.html','desc'=>'Explica específicamente el riesgo de aceptar como dirección del cliente valores provenientes de encabezados HTTP controlables y muestra ejemplos de headers utilizados para suplantar el origen.'],
 ['type'=>'Apache HTTP Server','title'=>'mod_remoteip','url'=>'https://httpd.apache.org/docs/2.4/mod/mod_remoteip.html','desc'=>'Muestra cómo debería configurarse un servidor para aceptar la IP declarada en X-Forwarded-For únicamente cuando procede de proxies internos o de confianza definidos explícitamente.'],
 ['type'=>'PortSwigger','title'=>'Spoofing your IP address using match and replace','url'=>'https://portswigger.net/burp/documentation/desktop/testing-workflow/vulnerabilities/access-controls/using-match-and-replace','desc'=>'Ejemplo práctico de una prueba de control de acceso basada en IP: modificar un encabezado que el servidor utiliza para determinar el origen de la petición.'],
 ['type'=>'MITRE ATT&CK ICS','title'=>'Remote Services','url'=>'https://attack.mitre.org/techniques/T0886/','desc'=>'Contextualiza el impacto de una frontera mal protegida entre una aplicación IT y servicios de una red operacional, sin requerir acceso directo al servicio OT interno.']
],
17=>[
 ['type'=>'Firefox DevTools','title'=>'Network Monitor · Request list','url'=>'https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/','desc'=>'Permite observar qué recursos carga la aplicación y qué peticiones realiza en segundo plano. Úsalo para distinguir documentos, JavaScript y llamadas de datos sin adivinar rutas.'],
 ['type'=>'Firefox DevTools','title'=>'Debugger · Search','url'=>'https://firefox-source-docs.mozilla.org/devtools-user/debugger/how_to/search/','desc'=>'Explica cómo buscar cadenas dentro del archivo actual o en todos los scripts del proyecto. Resulta útil para localizar términos como fetch, endpoint, api, telemetry o rutas /operations/ dentro del código cliente.'],
 ['type'=>'Firefox DevTools','title'=>'Network request details','url'=>'https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/request_details/','desc'=>'Muestra cómo inspeccionar URL, método, encabezados, cookies, respuesta y causa de una petición. Sirve para comparar una solicitud autenticada del HMI con una llamada directa al mismo servicio.'],
 ['type'=>'MDN','title'=>'Using the Fetch API','url'=>'https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch','desc'=>'Explica cómo JavaScript usa fetch() para realizar peticiones HTTP. Ayuda a reconocer en el código cliente qué endpoints consume una interfaz dinámica y qué información viaja en cada llamada.'],
 ['type'=>'OWASP WSTG','title'=>'Identify Application Entry Points','url'=>'https://wstg.owasp.org/latest/4-Web_Application_Security_Testing/01-Information_Gathering/06-Identify_Application_Entry_Points/','desc'=>'Metodología para inventariar puntos de entrada observando navegación, peticiones, parámetros y recursos del lado cliente. En este reto debe utilizarse antes de recurrir a enumeración o adivinación de URLs.'],
 ['type'=>'OWASP WSTG','title'=>'Testing for Bypassing Authorization Schema','url'=>'https://wstg.owasp.org/latest/4-Web_Application_Security_Testing/05-Authorization/02-Bypassing_Authorization_Schema/','desc'=>'Guía para comparar recursos protegidos y servicios auxiliares con y sin una sesión válida, verificando si todos aplican la misma decisión de autorización.'],
 ['type'=>'OWASP Cheat Sheet','title'=>'Authentication Cheat Sheet','url'=>'https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html','desc'=>'Aclara cómo se establece la identidad de un usuario y por qué estar en una red determinada no sustituye una autenticación de aplicación cuando se requiere conocer quién solicita el recurso.'],
 ['type'=>'OWASP Cheat Sheet','title'=>'Authorization Cheat Sheet','url'=>'https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html','desc'=>'Refuerza el principio de validar autorización en cada solicitud y no asumir que un endpoint auxiliar está protegido únicamente porque normalmente es llamado desde una interfaz autenticada.'],
 ['type'=>'OWASP Cheat Sheet','title'=>'REST Security Cheat Sheet','url'=>'https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html','desc'=>'Resume controles de autenticación y autorización para servicios HTTP. Es útil para analizar por qué una API de lectura también debe validar el contexto de seguridad del solicitante.'],
 ['type'=>'CWE','title'=>'CWE-306: Missing Authentication for Critical Function','url'=>'https://cwe.mitre.org/data/definitions/306.html','desc'=>'Describe el riesgo de exponer una función sensible sin comprobar una identidad cuando el recurso debería estar reservado a usuarios autenticados.'],
 ['type'=>'CWE','title'=>'CWE-862: Missing Authorization','url'=>'https://cwe.mitre.org/data/definitions/862.html','desc'=>'Complementa el análisis cuando existe un esquema de identidad o acceso general, pero una función concreta no comprueba si el solicitante está autorizado para utilizarla.'],
 ['type'=>'NIST','title'=>'SP 800-82 Rev. 3 · Guide to Operational Technology Security','url'=>'https://csrc.nist.gov/pubs/sp/800/82/r3/final','desc'=>'Contextualiza por qué la telemetría, las interfaces HMI y los servicios de soporte de OT requieren controles de acceso consistentes incluso dentro de segmentos de red restringidos.']
],
18=>[
 ['type'=>'Metodología','title'=>'Flujo de análisis offline de hashes','url'=>'https://www.kali.org/tools/hashid/','desc'=>'Empieza por clasificar el valor antes de intentar romperlo: conserva una copia original, separa prefijos descriptivos como sha1:, observa longitud y alfabeto, identifica si existe salt y confirma el formato con una herramienta. Sólo después elige el modo de cracking. En este laboratorio todo el análisis debe hacerse offline sobre el verificador proporcionado.'],
 ['type'=>'Kali Linux','title'=>'hashID · identificación de hashes','url'=>'https://www.kali.org/tools/hashid/','desc'=>'hashID reconoce más de un centenar de formatos y puede mostrar modos compatibles con Hashcat mediante -m. Es útil para confirmar que 40 caracteres hexadecimales son compatibles con SHA-1, pero la longitud por sí sola no constituye prueba suficiente: contrástala con el prefijo y el contexto del manifiesto.'],
 ['type'=>'Kali Linux','title'=>'hash-identifier','url'=>'https://www.kali.org/tools/hash-identifier/','desc'=>'Alternativa interactiva para identificar posibles tipos de hash. Úsala como segunda opinión cuando un digest pueda corresponder a varios formatos o construcciones.'],
 ['type'=>'Kali Linux','title'=>'Hashcat','url'=>'https://www.kali.org/tools/hashcat/','desc'=>'Herramienta principal para cracking offline. Para SHA-1 crudo consulta el modo 100. Flujo mínimo del laboratorio: guardar sólo el digest hexadecimal en un archivo; ejecutar hashcat -m 100 -a 0 hash.txt candidatos.txt; después consultar el resultado con hashcat -m 100 hash.txt --show. Empieza por diccionario antes de fuerza bruta.'],
 ['type'=>'Hashcat','title'=>'Hashcat Wiki · modos y ejemplos','url'=>'https://hashcat.net/wiki/doku.php?id=hashcat','desc'=>'Referencia para sintaxis, modos de ataque y uso de reglas. Los ataques de diccionario prueban candidatos de una lista; las reglas permiten transformar esos candidatos con mayúsculas, sufijos, números u otras mutaciones sin construir manualmente todas las variantes.'],
 ['type'=>'Kali Linux','title'=>'John the Ripper','url'=>'https://www.kali.org/tools/john/','desc'=>'Alternativa a Hashcat para análisis offline. Para un SHA-1 crudo puede utilizarse el formato raw-sha1 con una wordlist y luego john --show para recuperar el resultado. Es útil para comparar herramientas y confirmar un candidato sin depender de una sola implementación.'],
 ['type'=>'Openwall','title'=>'John the Ripper · cracking modes','url'=>'https://www.openwall.com/john/doc/MODES.shtml','desc'=>'Explica modos de diccionario, incremental y otras estrategias. Para este reto prioriza candidatos plausibles derivados del contexto antes de utilizar búsqueda exhaustiva.'],
 ['type'=>'Openwall','title'=>'John the Ripper · wordlist rules','url'=>'https://www.openwall.com/john/doc/RULES.shtml','desc'=>'Describe cómo las reglas transforman palabras base, por ejemplo cambios de mayúsculas y adición de dígitos. Es especialmente útil cuando el manifiesto sugiere términos como soporte, RTU, versión, build o números asociados a la actualización.'],
 ['type'=>'OWASP Cheat Sheet','title'=>'Password Storage Cheat Sheet','url'=>'https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html','desc'=>'Explica por qué SHA-1 y otras funciones rápidas no son adecuadas para almacenar contraseñas: permiten probar grandes cantidades de candidatos offline. Contrasta este residuo heredado con el bcrypt que utiliza el login moderno del laboratorio.'],
 ['type'=>'OWASP','title'=>'Cryptographic Failures','url'=>'https://top10.owasp.org/2025/A04_2025-Cryptographic_Failures/','desc'=>'Contextualiza el uso de algoritmos criptográficos obsoletos y recomienda funciones adaptativas y con salt para contraseñas. Ayuda a justificar por qué encontrar un SHA-1 heredado constituye un riesgo aunque el sistema actual use bcrypt.'],
 ['type'=>'OWASP','title'=>'IoT Security Testing Guide · Firmware','url'=>'https://owasp.org/owasp-istg/03_test_cases/firmware/index.html','desc'=>'Guía especializada para analizar firmware y mecanismos de actualización. Después de recuperar el acceso de mantenimiento, úsala para separar el análisis de credenciales del análisis del paquete de firmware.'],
 ['type'=>'CWE','title'=>'CWE-345: Insufficient Verification of Data Authenticity','url'=>'https://cwe.mitre.org/data/definitions/345.html','desc'=>'Distingue integridad de autenticidad: un contenido puede coincidir con un hash calculado por quien lo modificó sin demostrar que provenga de un emisor autorizado.'],
 ['type'=>'CWE','title'=>'CWE-347: Improper Verification of Cryptographic Signature','url'=>'https://cwe.mitre.org/data/definitions/347.html','desc'=>'Referencia para evaluar el paso final: una firma digital correctamente verificada sí puede aportar autenticidad cuando la clave pública confiable está anclada de forma adecuada.'],
 ['type'=>'NIST','title'=>'SP 800-193 · Platform Firmware Resiliency Guidelines','url'=>'https://csrc.nist.gov/pubs/sp/800/193/final','desc'=>'Presenta principios de protección, detección y recuperación de firmware. Úsalo para justificar qué propiedades debería verificar un proceso de actualización antes de aplicar un paquete.'],
 ['type'=>'NIST','title'=>'FIPS 180-4 · Secure Hash Standard','url'=>'https://csrc.nist.gov/pubs/fips/180-4/upd1/final','desc'=>'Referencia de SHA-1/SHA-2 y funciones hash. Ayuda a explicar qué significa recalcular un digest y por qué un hash sin secreto no autentica al creador de un paquete.'],
 ['type'=>'PowerShell','title'=>'Get-FileHash','url'=>'https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-filehash','desc'=>'Útil para documentar SHA-256 de archivos. Para cadenas exactas del payload, asegúrate de no introducir saltos de línea o caracteres adicionales: el digest cambia ante cualquier diferencia de bytes.']
],
19=>[
 ['type'=>'MITRE ATT&CK ICS','title'=>'ICS Matrix','url'=>'https://attack.mitre.org/matrices/ics/','desc'=>'Úsala para ordenar el encadenamiento entre acceso, descubrimiento, movimiento e impacto.'],
 ['type'=>'OWASP','title'=>'Web Security Testing Guide','url'=>'https://wstg.owasp.org/','desc'=>'Referencia para relacionar hallazgos web individuales dentro de una evaluación completa.']
],
20=>[
 ['type'=>'MITRE ATT&CK ICS','title'=>'Impact','url'=>'https://attack.mitre.org/tactics/TA0105/','desc'=>'Marco para comprender qué significa impacto sobre un proceso industrial sin confundirlo con simple acceso.'],
 ['type'=>'MITRE ATT&CK ICS','title'=>'Inhibit Response Function','url'=>'https://attack.mitre.org/tactics/TA0107/','desc'=>'Contexto sobre acciones que afectan supervisión, respuesta y funciones de protección en ICS.']
]
];
$pageTitle='Banderas'; include __DIR__.'/includes/header.php';
?>
<section class="hero compact"><div><p class="eyebrow">Captura y validación</p><h1>Banderas descubiertas</h1><p>El catálogo permanece oculto. Aquí puedes validar banderas, seguir una ruta de comprobación por reto y solicitar pistas progresivas sin revelar la solución.</p></div></section>
<?php if($msg):?><div class="alert success"><?=h($msg)?></div><?php endif;?><?php if($err):?><div class="alert error"><?=h($err)?></div><?php endif;?><?php if($hintMsg):?><div class="alert hint-alert"><?=h($hintMsg)?></div><?php endif;?>
<?php if(attempt_is_active()):?><section class="flag-tools"><article class="panel capture"><div class="panel-head"><div><p class="eyebrow">Validación</p><h2>Registrar bandera</h2></div></div><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="flag"><label>Bandera<input name="flag" placeholder="UPSLP_CNOIV-..." autocomplete="off" required></label><label>Nota <span class="optional">opcional</span><textarea name="note" rows="2" placeholder="Observación o referencia del hallazgo"></textarea></label><button class="primary" type="submit">Validar y registrar</button></form></article></section><?php endif;?>
<section class="panel guide-panel"><div class="panel-head"><div><p class="eyebrow">Ruta de validación</p><h2>Checklist de trabajo por reto</h2></div></div><p class="muted">No es un solucionario. Marca cada comprobación conforme la realices. El avance se guarda automáticamente en tu intento y permanece al volver a ingresar.</p><div class="challenge-guide-grid"><?php foreach($challengeChecklist as $no=>$items): $done=false; foreach($obtained as $of){if((int)$of['flag_number']===$no){$done=true;break;}} ?><article class="challenge-guide <?=$done?'done':''?>" id="reto-<?=sprintf('%02d',$no)?>"><div class="guide-head"><b>Reto <?=sprintf('%02d',$no)?></b><span><?=$done?'Acreditado':'Pendiente'?></span></div><div class="checklist-items"><?php foreach($items as $idx=>$item): $checked=$done || !empty($checkState[$no][$idx]); ?><label class="checklist-row <?=$checked?'checked':''?>"><input type="checkbox" class="challenge-check" data-flag="<?=$no?>" data-item="<?=$idx?>" <?=$checked?'checked':''?> <?=$done?'disabled':''?>> <span><?=h($item)?></span></label><?php endforeach;?></div><?php if(!empty($challengeResources[$no])):?><div class="research-resources"><div class="research-title"><span>⌕</span><b>Recursos para investigar</b></div><p>No contienen la solución de INTERAFAS. Úsalos para comprender el concepto y decidir qué comprobar.</p><?php foreach($challengeResources[$no] as $res):?><a class="research-link" href="<?=h($res['url'])?>" target="_blank" rel="noopener noreferrer"><span class="resource-type"><?=h($res['type'])?></span><span><b><?=h($res['title'])?></b><small><?=h($res['desc'])?></small></span><span class="external-mark">↗</span></a><?php endforeach;?></div><?php endif;?><div class="challenge-hints"><div class="research-title"><span>?</span><b>Pistas de este reto</b></div><?php if(!empty($usedHintsByFlag[$no])): ?><div class="challenge-hint-list"><?php foreach(array_reverse($usedHintsByFlag[$no]) as $hintRow): ?><div class="challenge-hint-entry"><small>Pista <?= (int)$hintRow['hint_order'] ?> · <?=h($hintRow['created_at'])?></small><p><?=h($hintRow['hint_text'])?></p></div><?php endforeach;?></div><?php else:?><p class="challenge-hint-empty">Todavía no has solicitado pistas para este reto.</p><?php endif;?><?php if(attempt_is_active() && !$done): ?><form method="post" action="/flags.php#reto-<?=sprintf('%02d',$no)?>" class="challenge-hint-form"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="hint"><input type="hidden" name="hint_flag" value="<?=$no?>"><button class="secondary" type="submit">Mostrar siguiente pista</button></form><?php elseif($done): ?><div class="challenge-hint-locked">Reto acreditado · no se requieren más pistas.</div><?php endif;?></div></article><?php endforeach;?></div></section><script>window.INTERAFAS_CSRF=<?=json_encode(csrf_token())?>;</script>
<section class="panel"><div class="panel-head"><div><p class="eyebrow">Hallazgos acreditados</p><h2><?=count($obtained)?> banderas descubiertas</h2></div></div>
<?php if(!$obtained):?><div class="empty">Todavía no has acreditado ninguna bandera.</div><?php else:?><div class="flag-grid discovered"><?php foreach($obtained as $f):?><article class="flag-card done"><div class="flag-no"><?=sprintf('%02d',$f['flag_number'])?></div><div><span class="pill"><?=str_repeat('★',(int)$f['difficulty'])?> · <?=$f['weight']?> pt</span><h3><?=h($f['code_name'])?></h3><p><?=h($f['title'])?></p><small><?=h($f['category'])?><?= $f['triggers_phase'] ? ' · disparó F'.$f['triggers_phase'] : '' ?></small><b class="obtained">✓ <?=h($f['obtained_at'])?></b></div></article><?php endforeach;?></div><?php endif;?></section>
<section class="panel hint-history"><div class="panel-head"><div><p class="eyebrow">Historial global</p><h2>Registro de pistas solicitadas</h2></div><span class="pill"><?=count($usedHints)?> consultas</span></div><?php if(!$usedHints):?><div class="empty">Aún no has solicitado pistas. Cuando lo hagas, quedarán almacenadas aquí con su reto, nivel y fecha.</div><?php else:?><?php $grouped=[]; foreach($usedHints as $uh){$grouped[(int)$uh['flag_number']][]=$uh;} ksort($grouped); ?><div class="hint-groups"><?php foreach($grouped as $flagNo=>$rows):?><article class="hint-group"><div class="hint-group-title"><b>Reto <?=sprintf('%02d',$flagNo)?></b><span><?=count($rows)?> pista<?=count($rows)===1?'':'s'?></span></div><?php foreach(array_reverse($rows) as $h):?><div class="hint-entry"><small><?=h($h['created_at'])?> · Pista <?= (int)$h['hint_order']?></small><p><?=h($h['hint_text'])?></p></div><?php endforeach;?></article><?php endforeach;?></div><?php endif;?></section>
<?php include __DIR__.'/includes/footer.php'; ?>
