<?php $pageTitle='Portada'; require_once __DIR__.'/includes/config.php'; $articles=visible_articles(); $lead=$articles[0]??null; $secondary=array_slice($articles,1,4); $latest=array_slice($articles,5,12); include __DIR__.'/includes/header.php'; ?>
<?php if(special_interafas_unlocked() && $state['phase']>=1): ?><div class="breaking"><div class="wrap"><b>ÚLTIMA HORA</b><span><?= h($state['phase_name']) ?></span><a href="/especial.php">COBERTURA EN VIVO →</a></div></div><?php endif; ?>
<section class="wrap newsroom-top">
  <?php if($lead): $lm=media_info($lead['hero_asset']); ?>
  <article class="lead-story" data-news-id="<?= (int)$lead['id'] ?>" data-news-new="<?= article_is_new($lead,$state)?'1':'0' ?>" data-interafas="<?= ((int)$lead['phase_required']>0 || !empty($lead['event_required']))?'1':'0' ?>"><a href="/nota.php?slug=<?= h($lead['slug']) ?>"><div class="lead-photo"><img src="<?= h($lm['src']) ?>" onerror="this.onerror=null;this.src='<?= h($lm['fallback']) ?>'" alt=""><span class="live-tag"><?= $lead['breaking']?'ÚLTIMA HORA':'EN DESARROLLO' ?></span></div><span class="kicker"><?= h($lead['category']) ?></span><h1><?= h($lead['headline']) ?></h1><p><?= h($lead['subheadline']) ?></p><div class="story-meta">Por <?= h($lead['author']) ?> · <?= article_time($lead) ?></div></a></article>
  <?php endif; ?>
  <aside class="top-rail"><div class="rail-title">AHORA</div><?php foreach($secondary as $a): ?><article data-news-id="<?= (int)$a['id'] ?>" data-news-new="<?= article_is_new($a,$state)?'1':'0' ?>" data-interafas="<?= ((int)$a['phase_required']>0 || !empty($a['event_required']))?'1':'0' ?>"><a href="/nota.php?slug=<?= h($a['slug']) ?>"><time><?= article_time($a) ?></time><span class="kicker"><?= h($a['category']) ?> · <?= article_time($a) ?></span><h2><?= h($a['headline']) ?></h2></a></article><?php endforeach; ?><a class="more-link" href="/archivo.php">Ver todas las noticias →</a></aside>
</section>
<?php if(special_interafas_unlocked()):?><section class="black-band"><div class="wrap"><div><span class="eyebrow">COBERTURA ESPECIAL</span><h2>INTERAFAS: seguimiento minuto a minuto</h2><p>La información pública cambia conforme se confirman nuevos hechos del incidente.</p></div><a href="/especial.php">Entrar a la cobertura →</a></div></section><?php endif;?>
<section class="wrap latest"><div class="section-title"><h2>Últimas noticias</h2><a href="/archivo.php">Archivo completo</a></div><div class="cards"><?php foreach($latest as $a): $m=media_info($a['hero_asset']); ?><article data-news-id="<?= (int)$a['id'] ?>" data-news-new="<?= article_is_new($a,$state)?'1':'0' ?>" data-interafas="<?= ((int)$a['phase_required']>0 || !empty($a['event_required']))?'1':'0' ?>"><a href="/nota.php?slug=<?= h($a['slug']) ?>"><img src="<?= h($m['src']) ?>" onerror="this.onerror=null;this.src='<?= h($m['fallback']) ?>'" alt=""><div class="card-copy"><div class="card-time"><?= article_time($a) ?> · <?= h(strtoupper($a['category'])) ?></div><h3><?= h($a['headline']) ?></h3><p><?= h($a['subheadline']) ?></p></div></a></article><?php endforeach; ?></div></section>
<script>window.PULSO_LIVE=true;</script><?php include __DIR__.'/includes/footer.php'; ?>
