-- v0.4.8 · Cada FLAG libera cobertura periodística y conversación social.
SET NAMES utf8mb4;
ALTER TABLE news_articles CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE scenario_social_posts CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
INSERT IGNORE INTO news_articles (phase_required,event_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking) VALUES (0,'FLAG_01',0,'local','archivo-publico-genera-preguntas','Respaldo de despliegue queda expuesto junto a documentos públicos de INTERAFAS','Un archivo ZIP generado durante una actualización del portal quedó accesible en la misma ruta usada para documentos públicos.','Un archivo de respaldo generado durante una actualización del portal de INTERAFAS quedó accesible junto a documentos públicos de contratación. El ZIP contiene un manifiesto de versión, notas de despliegue, un registro de sincronización y archivos auxiliares utilizados por el equipo web. El hallazgo no demuestra por sí mismo una intrusión, pero evidencia que un artefacto temporal permaneció bajo el directorio público después del despliegue.

Fuentes técnicas del organismo indicaron que el archivo debió eliminarse al concluir la sincronización de la versión. El equipo de Tecnologías revisa ahora el procedimiento de despliegue y la configuración del servidor que permitió listar el contenido del directorio. Especialistas consultados por Pulso Metropolitano señalan que respaldos y residuos de publicación pueden revelar nombres internos, rutas, versiones y hábitos operativos útiles para reconocimiento posterior.

INTERAFAS informó que retirará de manera preventiva cualquier documento cuya publicación no pueda justificarse y anunció una revisión de inventario. La institución insistió en que, hasta el momento, no existe evidencia de afectación al servicio.','Unidad Digital','photo-evidence',46,0,0);
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_01',0,'@pulso_flag_01','Conversación Metro','Metropolitano','Conversación','¿Alguien más vio el ZIP que apareció junto a los PDF de contratos? Parece de una actualización del portal.',27,5,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@pulso_flag_01');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_01',0,'@reaccion_flag_01','Voces Metropolitanas','Metropolitano','Conversación','Si eso era “interno”, alguien debería explicar por qué estaba a un clic.',24,5,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@reaccion_flag_01');
INSERT IGNORE INTO news_articles (phase_required,event_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking) VALUES (0,'FLAG_02',0,'tecnologia','codigo-cliente-revela-pistas','Código visible en el navegador revela más de lo que parece','Analistas advierten que comentarios, rutas y variables expuestas del lado del cliente pueden ayudar a reconstruir la arquitectura de un sistema.','Una revisión del código entregado al navegador por el portal de INTERAFAS permitió observar referencias internas que no eran necesarias para el funcionamiento público. Aunque se trata de información disponible para cualquier usuario, especialistas consideran que la acumulación de pequeños detalles puede facilitar el reconocimiento de una plataforma.

El equipo de Tecnologías confirmó que revisará scripts, comentarios y configuraciones expuestas en el frontend. “Que algo esté en el navegador no significa que sea secreto, pero tampoco significa que debamos regalar contexto innecesario”, señaló una fuente técnica del organismo.

La institución no reportó interrupciones y mantiene el portal operando con normalidad. La revisión se incorporó al programa de endurecimiento de aplicaciones.','Mesa de Tecnología','photo-cyber',47,0,0);
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_02',0,'@pulso_flag_02','Conversación Metro','Metropolitano','Conversación','Hay gente revisando hasta el código de la página. Internet nunca perdona un comentario olvidado.',34,7,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@pulso_flag_02');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_02',0,'@reaccion_flag_02','Voces Metropolitanas','Metropolitano','Conversación','Mi teoría: cada “detalle sin importancia” termina siendo una pieza del rompecabezas.',33,8,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@reaccion_flag_02');
INSERT IGNORE INTO news_articles (phase_required,event_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking) VALUES (0,'FLAG_03',0,'servicios','usuarios-reportan-datos-cruzados','Usuarios reportan acceso cruzado a información de cuentas de servicio','INTERAFAS investiga si una falla de autorización permitió consultar datos asociados con contratos ajenos.','INTERAFAS inició una revisión después de recibir reportes sobre información de cuentas de servicio que podía mostrarse al modificar referencias dentro de una solicitud web. El organismo señaló que aún determina el alcance y cuántos registros pudieron quedar expuestos.

Especialistas explican que este tipo de falla no depende de adivinar contraseñas, sino de verificar correctamente que cada usuario tenga permiso para consultar el objeto solicitado. Una referencia numérica predecible puede convertirse en un problema si el servidor confía únicamente en que el usuario “no debería cambiarla”.

Atención Ciudadana pidió a los usuarios reportar cualquier información que no corresponda a su cuenta y anunció una revisión de accesos recientes.','Unidad de Servicios','photo-control',48,0,1);
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_03',0,'@pulso_flag_03','Conversación Metro','Metropolitano','Conversación','Me apareció información que claramente no era de mi cuenta. Eso sí me preocupa.',41,9,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@pulso_flag_03');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_03',0,'@reaccion_flag_03','Voces Metropolitanas','Metropolitano','Conversación','No quiero descuento ni disculpa: quiero saber quién puede ver mis datos y por qué.',42,11,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@reaccion_flag_03');
INSERT IGNORE INTO news_articles (phase_required,event_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking) VALUES (0,'FLAG_04',0,'tecnologia','respaldo-historico-expuesto','Aparece respaldo histórico del portal en una ubicación pública','El archivo conserva componentes de una versión anterior y reactiva dudas sobre la gestión de copias de seguridad.','Un respaldo histórico del portal de INTERAFAS fue localizado en una ruta accesible desde Internet. El archivo corresponde a una versión anterior de la aplicación y contiene recursos que ya no forman parte de la publicación principal.

Especialistas señalan que los respaldos web suelen convertirse en una fuente de información valiosa para un atacante porque pueden conservar código antiguo, configuraciones o estructuras de directorios. INTERAFAS indicó que el archivo fue retirado y que revisará los procedimientos de respaldo y despliegue.

La institución no ha confirmado que el contenido haya sido utilizado de forma maliciosa, pero abrió una revisión de registros para conocer cuántas veces fue descargado.','Mesa de Tecnología','photo-evidence',49,0,0);
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_04',0,'@pulso_flag_04','Conversación Metro','Metropolitano','Conversación','El clásico backup.zip viviendo su mejor vida en producción 😭',48,11,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@pulso_flag_04');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_04',0,'@meme_flag_04','Memes Metropolitanos','Metropolitano','Humor','Ya empezaron los memes sobre el hallazgo. Internet tarda menos que cualquier comité.',132,40,NULL,'ADMINISTRACIÓN DE RESPALDOS','Nivel: “déjalo ahí, nadie lo va a encontrar”.' WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@meme_flag_04');
INSERT IGNORE INTO news_articles (phase_required,event_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking) VALUES (0,'FLAG_05',0,'tecnologia','errores-tecnicos-exponen-detalles','Mensajes de error del portal muestran detalles internos del sistema','Capturas compartidas por usuarios revelan rutas y nombres técnicos que no deberían formar parte de una respuesta pública.','Capturas del portal ciudadano muestran mensajes de error con detalles sobre componentes internos de la aplicación. Aunque los mensajes surgieron durante operaciones fallidas, especialistas consideran que la información técnica puede ayudar a perfilar la plataforma.

INTERAFAS explicó que los sistemas de producción deberían mostrar mensajes genéricos al usuario y enviar el detalle completo únicamente a registros internos. El equipo técnico revisará configuraciones de depuración y manejo de excepciones.

No se reportó pérdida de servicio. Sin embargo, el incidente se suma a una serie de señales que han motivado una revisión más amplia del ciclo de desarrollo y publicación.','Mesa de Tecnología','photo-cyber',50,0,0);
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_05',0,'@pulso_flag_05','Conversación Metro','Metropolitano','Conversación','Los errores enseñan más del servidor que algunos manuales.',55,13,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@pulso_flag_05');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_05',0,'@reaccion_flag_05','Voces Metropolitanas','Metropolitano','Conversación','Pantalla roja con ruta completa: gracias por el tour técnico, supongo.',60,17,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@reaccion_flag_05');
INSERT IGNORE INTO news_articles (phase_required,event_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking) VALUES (0,'FLAG_06',0,'servicios','funcion-restringida-accesible','Función restringida aparece disponible para usuarios sin el rol previsto','La institución revisa controles de autorización después de detectar una operación que podía ejecutarse fuera del perfil correspondiente.','INTERAFAS investiga una inconsistencia en los controles de acceso del portal ciudadano después de detectar que una función reservada para ciertos perfiles podía ser solicitada por usuarios con permisos menores.

La diferencia entre ocultar un botón y bloquear realmente una operación en el servidor es clave, explicaron especialistas consultados. Si el control existe solo en la interfaz, una solicitud directa puede eludirlo.

La institución indicó que revisará todas las funciones sensibles y no únicamente la ruta reportada. Hasta ahora no ha informado afectaciones financieras ni cambios irreversibles.','Unidad de Servicios','photo-control',51,0,0);
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_06',0,'@pulso_flag_06','Conversación Metro','Metropolitano','Conversación','Ocultar el botón no es seguridad. Hoy aprendimos todos.',62,15,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@pulso_flag_06');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_06',0,'@reaccion_flag_06','Voces Metropolitanas','Metropolitano','Conversación','Si mi usuario no tiene permiso, el servidor debería decir no. Punto.',69,20,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@reaccion_flag_06');
INSERT IGNORE INTO news_articles (phase_required,event_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking) VALUES (0,'FLAG_07',0,'investigacion','consulta-proveedores-responde-de-forma-anomala','Consulta de proveedores muestra comportamiento anómalo ante entradas manipuladas','El patrón de respuesta activa una revisión de seguridad sobre cómo el portal procesa búsquedas y filtros.','Una función de búsqueda relacionada con proveedores comenzó a ser revisada después de que pruebas controladas detectaran diferencias consistentes ante determinados valores de entrada. La aplicación no muestra errores directos, pero su comportamiento sugiere que la validación merece una revisión más profunda.

Especialistas explican que las vulnerabilidades de inyección no siempre producen mensajes evidentes; algunas solo pueden inferirse comparando respuestas, tiempos o condiciones. INTERAFAS informó que aplicará consultas parametrizadas y validaciones adicionales.

La revisión se mantiene en curso y la institución no ha confirmado acceso a información sensible.','Unidad de Investigación','photo-cyber',52,0,1);
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_07',0,'@pulso_flag_07','Conversación Metro','Metropolitano','Conversación','La búsqueda de proveedores se comporta raro con ciertos caracteres. Qué casualidad.',69,17,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@pulso_flag_07');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_07',0,'@reaccion_flag_07','Voces Metropolitanas','Metropolitano','Conversación','Cuando una búsqueda tarda justo distinto según lo que escribes… 👀',78,23,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@reaccion_flag_07');
INSERT IGNORE INTO news_articles (phase_required,event_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking) VALUES (0,'FLAG_08',0,'comunidad','comentario-alterado-permanece-visible','Contenido enviado por usuarios reaparece sin el tratamiento esperado','Moderadores detectan que ciertas entradas permanecen almacenadas y se muestran a otros visitantes.','El equipo de moderación de INTERAFAS revisa una falla en el tratamiento de contenido enviado por usuarios después de observar que determinadas entradas permanecían almacenadas y podían reproducirse en visitas posteriores.

El problema pone el foco en la necesidad de separar texto de instrucciones interpretables por el navegador. Especialistas recuerdan que cualquier contenido aportado por terceros debe codificarse antes de mostrarse.

La institución deshabilitó temporalmente la función afectada mientras se revisan publicaciones existentes y controles de sanitización.','Comunidad','photo-press',53,0,0);
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_08',0,'@pulso_flag_08','Conversación Metro','Metropolitano','Conversación','Ya vi el comentario extraño replicándose. Moderación va a tener tarde larga.',76,19,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@pulso_flag_08');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_08',0,'@reaccion_flag_08','Voces Metropolitanas','Metropolitano','Conversación','Internet: “solo era un comentario”. Navegador: “entiendo, ejecutaré la creatividad”.',87,26,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@reaccion_flag_08');
INSERT IGNORE INTO news_articles (phase_required,event_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking) VALUES (0,'FLAG_09',0,'investigacion','descargas-permiten-salir-de-ruta','Módulo de documentos permite solicitar rutas fuera del directorio previsto','INTERAFAS restringe descargas mientras revisa la forma en que la aplicación construye rutas de archivo.','El módulo de documentos de INTERAFAS fue restringido después de que una prueba interna demostrara que ciertas solicitudes podían intentar salir del directorio destinado a archivos públicos.

La institución explicó que los nombres proporcionados por el usuario nunca deberían convertirse directamente en rutas del sistema. La corrección incluirá listas permitidas, normalización de rutas y separación física de archivos sensibles.

El análisis forense busca determinar si hubo acceso efectivo a recursos no autorizados o únicamente intentos dentro del entorno de prueba.','Unidad de Investigación','photo-evidence',54,0,0);
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_09',0,'@pulso_flag_09','Conversación Metro','Metropolitano','Conversación','Descargar documentos no debería sentirse como explorar el servidor completo.',83,21,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@pulso_flag_09');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_09',0,'@reaccion_flag_09','Voces Metropolitanas','Metropolitano','Conversación','Ese módulo necesita límites, no fe en que nadie cambie la ruta.',96,29,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@reaccion_flag_09');
INSERT IGNORE INTO news_articles (phase_required,event_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking) VALUES (0,'FLAG_10',0,'tecnologia','sesiones-requieren-revision','INTERAFAS revisa manejo de sesiones después de detectar inconsistencias','El organismo analiza duración, invalidación y controles asociados con la identidad del usuario.','INTERAFAS inició una revisión de su administración de sesiones después de detectar comportamientos que podían permitir que una sesión continuara siendo útil más tiempo del previsto o bajo condiciones distintas a las esperadas.

La gestión de sesiones es uno de los puntos más sensibles de un portal ciudadano porque concentra la identidad ya autenticada. Revocar correctamente sesiones, rotar identificadores y validar acciones críticas reduce el impacto de un posible robo o reutilización.

El organismo anunció cambios preventivos y podría forzar nuevos inicios de sesión mientras concluyen las pruebas.','Mesa de Tecnología','photo-control',55,0,0);
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_10',0,'@pulso_flag_10','Conversación Metro','Metropolitano','Conversación','Me volvió a pedir iniciar sesión. Si es por seguridad, bien; avisen nada más.',90,23,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@pulso_flag_10');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_10',0,'@reaccion_flag_10','Voces Metropolitanas','Metropolitano','Conversación','Prefiero volver a entrar que descubrir que una sesión dura para siempre.',105,32,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@reaccion_flag_10');
INSERT IGNORE INTO news_articles (phase_required,event_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking) VALUES (0,'FLAG_11',0,'investigacion','api-no-documentada-aparece-en-revision','Una API no documentada aparece durante la revisión del portal','La ruta amplía el mapa de servicios internos y genera preguntas sobre inventario y exposición.','Una interfaz de programación no documentada públicamente fue localizada durante la revisión técnica de INTERAFAS. La ruta responde desde la misma infraestructura del portal y expone funciones que no aparecen en la navegación convencional.

Especialistas señalan que los servicios olvidados o sin inventario suelen escapar de controles de mantenimiento y monitoreo. INTERAFAS indicó que verificará propietario, propósito, autenticación y necesidad operativa de cada endpoint.

El hallazgo no implica por sí mismo una vulneración, pero amplía la superficie que el equipo deberá auditar.','Unidad de Investigación','photo-cyber',56,0,0);
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_11',0,'@pulso_flag_11','Conversación Metro','Metropolitano','Conversación','¿Por qué hay una API que nadie menciona en la documentación pública?',97,25,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@pulso_flag_11');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_11',0,'@reaccion_flag_11','Voces Metropolitanas','Metropolitano','Conversación','Inventario de sistemas: ese Excel que todos juran que existe.',114,35,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@reaccion_flag_11');
INSERT IGNORE INTO news_articles (phase_required,event_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking) VALUES (0,'FLAG_12',0,'servicios','api-muestra-cuenta-distinta','API de servicios devuelve información asociada con otra cuenta','La revisión se centra en autorización por objeto y en la exposición potencial de información de usuarios.','La investigación del portal ciudadano detectó que una API podía devolver información de una cuenta de servicio distinta cuando se modificaba su identificador. INTERAFAS analiza el número de registros potencialmente consultables y los accesos realizados.

El hallazgo es relevante porque una aplicación puede autenticar correctamente a un usuario y aun así fallar al autorizar qué objetos específicos puede consultar. Ese tipo de error afecta directamente la confidencialidad de datos.

El organismo restringió temporalmente la función y notificó a sus equipos jurídico y de protección de datos para evaluar obligaciones adicionales.','Unidad de Servicios','photo-evidence',57,0,1);
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_12',0,'@pulso_flag_12','Conversación Metro','Metropolitano','Conversación','Otra cuenta, mismos endpoints. Esto ya dejó de parecer un error visual.',104,27,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@pulso_flag_12');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_12',0,'@reaccion_flag_12','Voces Metropolitanas','Metropolitano','Conversación','Si cambias un número y aparece otro usuario, tenemos problema.',123,38,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@reaccion_flag_12');
INSERT IGNORE INTO news_articles (phase_required,event_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking) VALUES (0,'FLAG_13',0,'economia','flujo-pago-bajo-revision','Flujo de pago digital entra a revisión por una inconsistencia de lógica','Especialistas analizan si ciertos parámetros podían modificar el resultado esperado sin romper técnicamente la aplicación.','El módulo de pagos de INTERAFAS fue incluido en una revisión especial después de detectar una inconsistencia en la lógica con la que valida referencias, montos y estados de una operación.

A diferencia de un error puramente técnico, las fallas de lógica de negocio aparecen cuando el sistema ejecuta exactamente lo programado, pero permite secuencias que contradicen las reglas del servicio. La institución revisa si alguna transacción real pudo verse afectada.

INTERAFAS señaló que conciliará operaciones recientes y reforzará verificaciones del lado del servidor antes de confirmar pagos.','Economía','photo-distribution',58,0,0);
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_13',0,'@pulso_flag_13','Conversación Metro','Metropolitano','Conversación','En pagos, “funciona” no significa “cumple las reglas”.',111,29,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@pulso_flag_13');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_13',0,'@reaccion_flag_13','Voces Metropolitanas','Metropolitano','Conversación','La lógica de negocio también se hackea; no todo son puertos y contraseñas.',132,41,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@reaccion_flag_13');
INSERT IGNORE INTO news_articles (phase_required,event_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking) VALUES (0,'FLAG_14',0,'investigacion','proveedores-permisos-cruzados','Revisión de contrataciones detecta permisos cruzados entre proveedor y contrato','El hallazgo abre preguntas sobre segregación de funciones y administración de terceros.','Una revisión del módulo de contrataciones detectó que ciertas relaciones entre proveedores, contratos y documentos podían consultarse o modificarse con permisos más amplios de lo necesario.

La administración de terceros es especialmente sensible porque concentra documentos, anexos y procesos que cruzan varias áreas. Especialistas recomiendan controles por rol, por objeto y trazabilidad de cada modificación.

INTERAFAS informó que Jurídico, Administración y Tecnologías participan ya en una revisión conjunta del módulo.','Unidad de Investigación','photo-press',59,0,0);
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_14',0,'@pulso_flag_14','Conversación Metro','Metropolitano','Conversación','Contratos, proveedores y permisos mezclados: receta para auditoría de fin de semana.',118,31,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@pulso_flag_14');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_14',0,'@reaccion_flag_14','Voces Metropolitanas','Metropolitano','Conversación','A ver si ahora sí publican quién puede tocar qué en contrataciones.',141,44,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@reaccion_flag_14');
INSERT IGNORE INTO news_articles (phase_required,event_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking) VALUES (0,'FLAG_15',0,'investigacion','configuracion-interna-revela-arquitectura','Archivo de configuración expone referencias a servicios internos de INTERAFAS','El hallazgo conecta por primera vez el portal público con componentes que no deberían ser visibles desde Internet.','La revisión del portal de INTERAFAS encontró referencias a nombres y servicios internos que permiten reconstruir parte de la arquitectura detrás de la aplicación pública. Aunque no constituyen acceso directo, las referencias son relevantes porque muestran dependencias que deberían permanecer separadas.

Especialistas consultados advierten que la información arquitectónica reduce la incertidumbre de un atacante y puede orientar intentos hacia sistemas más sensibles. INTERAFAS inició una revisión de secretos, configuraciones y segmentación.

El organismo aseguró que los componentes operacionales continúan bajo controles independientes, aunque confirmó que el hallazgo elevó la prioridad del análisis.','Unidad de Investigación','photo-scada',60,0,1);
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_15',0,'@pulso_flag_15','Conversación Metro','Metropolitano','Conversación','Ya están hablando de nombres internos y arquitectura. Esto escaló rápido.',125,33,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@pulso_flag_15');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_15',0,'@reaccion_flag_15','Voces Metropolitanas','Metropolitano','Conversación','Cuando el mapa interno aparece en un archivo público, el atacante deja de caminar a ciegas.',150,47,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@reaccion_flag_15');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_16',0,'@flag16_extra','Voces Metropolitanas','Metropolitano','Conversación','Cuadrillas afuera y el mapa cambiando. Ya no parece un reporte aislado.',356,109,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@flag16_extra');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_16',0,'@flag16_extra2','Voces Metropolitanas','Metropolitano','Conversación','Primero dijeron normalidad, ahora hablan de anomalías. Necesitamos tiempos y zonas claras.',379,118,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@flag16_extra2');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_17',0,'@flag17_extra','Voces Metropolitanas','Metropolitano','Conversación','Si ya confirmaron incidente tecnológico, publiquen qué servicios están aislados y cuáles siguen confiables.',367,113,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@flag17_extra');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_17',0,'@flag17_extra2','Voces Metropolitanas','Metropolitano','Conversación','La gente está llenando grupos de capturas. Comunicación oficial tiene que ir más rápido.',390,122,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@flag17_extra2');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_18',0,'@flag18_extra','Voces Metropolitanas','Metropolitano','Conversación','Cuando operación y tecnología empiezan a hablar juntos, sabes que el asunto ya cruzó fronteras internas.',378,117,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@flag18_extra');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_18',0,'@flag18_extra2','Voces Metropolitanas','Metropolitano','Conversación','¿Firmware en medio de una crisis? Esta temporada viene con demasiados giros.',401,126,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@flag18_extra2');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_19',0,'@flag19_extra','Voces Metropolitanas','Metropolitano','Conversación','Ya no es una falla: es una cadena. Y ahora todos quieren saber dónde empezó.',389,121,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@flag19_extra');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_19',0,'@flag19_extra2','Voces Metropolitanas','Metropolitano','Conversación','Contratos, accesos, sistemas internos… cada respuesta abre tres preguntas nuevas.',412,130,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@flag19_extra2');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_20',0,'@flag20_extra','Voces Metropolitanas','Metropolitano','Conversación','Esto ya dejó de ser “tema de sistemas”. Hay consecuencias en la calle.',400,125,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@flag20_extra');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption) SELECT 0,'FLAG_20',0,'@flag20_extra2','Voces Metropolitanas','Metropolitano','Conversación','Que investiguen todo, pero primero que estabilicen el servicio y atiendan a la gente.',423,134,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@flag20_extra2');
