-- v0.5.0 · Auditor refinement, navigation telemetry and progressive hints
CREATE TABLE IF NOT EXISTS flag_hints (
  flag_number INT NOT NULL,
  hint_order TINYINT NOT NULL,
  hint_text VARCHAR(500) NOT NULL,
  PRIMARY KEY(flag_number,hint_order),
  CONSTRAINT fk_hint_catalog FOREIGN KEY(flag_number) REFERENCES flag_catalog(flag_number)
);
CREATE TABLE IF NOT EXISTS lab_hint_usage (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  attempt_id INT NOT NULL,
  student_id INT NOT NULL,
  flag_number INT NOT NULL,
  hint_order TINYINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_attempt_hint(attempt_id,flag_number,hint_order),
  INDEX idx_hint_usage_attempt(attempt_id,created_at),
  CONSTRAINT fk_hint_usage_attempt FOREIGN KEY(attempt_id) REFERENCES lab_attempts(id),
  CONSTRAINT fk_hint_usage_student FOREIGN KEY(student_id) REFERENCES lab_students(id),
  CONSTRAINT fk_hint_usage_catalog FOREIGN KEY(flag_number) REFERENCES flag_catalog(flag_number)
);
INSERT INTO flag_hints(flag_number,hint_order,hint_text) VALUES
(1,1,'Empieza por una comprobación básica que muchos olvidan: revisa qué rutas pide el propio sitio que los buscadores no indexen.'),
(1,2,'Un servidor puede mostrar más de lo que la aplicación decidió enlazar. Revisa nombres y artefactos que parezcan residuales.'),
(2,1,'Mira más allá de lo que el navegador renderiza visualmente.'),
(2,2,'El código fuente y los recursos del cliente también cuentan una historia.'),
(3,1,'Compara identificadores cuando consultas información de una cuenta.'),
(3,2,'Pregúntate si el servidor valida que ese objeto realmente te pertenece.'),
(4,1,'Los archivos antiguos suelen sobrevivir a los cambios de versión.'),
(4,2,'Busca nombres de respaldo, copias y extensiones que un administrador pudo olvidar.'),
(5,1,'Provoca entradas inesperadas y observa qué información devuelve la aplicación.'),
(5,2,'Un error demasiado descriptivo puede revelar estructura interna.'),
(6,1,'Compara lo que puede hacer un usuario normal frente a otra función del portal.'),
(6,2,'No confíes en que ocultar un botón equivale a autorizar una acción.'),
(7,1,'Observa diferencias pequeñas en la respuesta cuando cambias una condición.'),
(7,2,'No necesitas ver un error SQL para inferir si una condición es verdadera o falsa.'),
(8,1,'Busca campos cuyo contenido vuelva a mostrarse posteriormente a otros usuarios.'),
(8,2,'Piensa en entradas persistentes que el navegador interpreta, no solo muestra.'),
(9,1,'Examina cómo el servidor decide qué archivo entregar.'),
(9,2,'Prueba si una ruta solicitada puede escapar del directorio previsto dentro del laboratorio.'),
(10,1,'Observa qué cambia —y qué no— cuando una sesión inicia, termina o se reutiliza.'),
(10,2,'Revisa cookies, identificadores y controles que deberían invalidarse.'),
(11,1,'No todos los endpoints aparecen en la interfaz.'),
(11,2,'Revisa recursos, scripts y patrones de rutas que sugieran una API no documentada.'),
(12,1,'Una API también debe validar la propiedad del objeto solicitado.'),
(12,2,'Compara respuestas al variar identificadores de cuentas de servicio.'),
(13,1,'Sigue el flujo completo de pago, no solo el formulario visible.'),
(13,2,'Busca qué valores confía el servidor entre una etapa y la siguiente.'),
(14,1,'Relaciona proveedores, contratos y permisos como entidades separadas.'),
(14,2,'Un vínculo válido entre dos registros no significa que el usuario esté autorizado a alterarlo.'),
(15,1,'La arquitectura interna suele asomarse en configuraciones, errores o documentación operativa.'),
(15,2,'Busca referencias a nombres de servicios, hosts o redes que el usuario común no necesita conocer.'),
(16,1,'Identifica dónde termina la aplicación pública y comienza la infraestructura operacional.'),
(16,2,'Busca una puerta de enlace o ruta que conecte el entorno IT con servicios internos.'),
(17,1,'Una interfaz de monitoreo debería exigir autorización propia.'),
(17,2,'Si encuentras el HMI, comprueba qué valida realmente antes de mostrar variables.'),
(18,1,'Analiza qué valida el actualizador antes de aceptar un paquete.'),
(18,2,'Integridad y autenticidad no son lo mismo: revisa manifiesto, hash y firma del firmware ficticio.'),
(19,1,'Esta bandera no depende de un solo fallo.'),
(19,2,'Relaciona lo descubierto en web, arquitectura, HMI y mantenimiento para reconstruir una cadena completa.'),
(20,1,'El objetivo final es demostrar impacto operacional simulado, no solo acceso.'),
(20,2,'Busca qué acción autorizada por la cadena previa modifica el estado de P-101 dentro del simulador.')
ON DUPLICATE KEY UPDATE hint_text=VALUES(hint_text);
