SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER DATABASE interafas CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE scenario_social_posts CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- INTERAFAS v0.4.6 · continuidad narrativa
ALTER TABLE afectaciones ADD COLUMN IF NOT EXISTS event_required VARCHAR(100) NULL AFTER prioridad;
ALTER TABLE afectaciones ADD INDEX IF NOT EXISTS idx_afectacion_event (event_required);
ALTER TABLE scenario_social_posts ADD COLUMN IF NOT EXISTS meme_title VARCHAR(180) NULL AFTER avatar_url;
ALTER TABLE scenario_social_posts ADD COLUMN IF NOT EXISTS meme_caption VARCHAR(320) NULL AFTER meme_title;

-- Afectaciones que aparecen conforme avanza el incidente.
INSERT INTO afectaciones (titulo,tipo,estado,municipio,sector,descripcion,inicio,fin_estimado,cuentas_estimadas,x_pct,y_pct,prioridad,event_required)
SELECT 'Variaciones de presión en corredor norte','Baja presión','En atención','Saint Louis','Corredor Norte','Se investigan variaciones simultáneas de presión. Cuadrillas verifican estaciones, tanques y válvulas de regulación.','2026-09-23 09:10:00','2026-09-23 13:00:00',6840,51,24,'Alta','FLAG_16'
WHERE NOT EXISTS (SELECT 1 FROM afectaciones WHERE event_required='FLAG_16' AND titulo='Variaciones de presión en corredor norte');
INSERT INTO afectaciones (titulo,tipo,estado,municipio,sector,descripcion,inicio,fin_estimado,cuentas_estimadas,x_pct,y_pct,prioridad,event_required)
SELECT 'Contingencia por indisponibilidad de monitoreo remoto','Incidente tecnológico','En atención','Cerro de San Pablo','Zona Centro','Operadores realizan validación en campo mientras se restringen funciones de supervisión remota.','2026-09-23 10:45:00','2026-09-23 16:30:00',4250,27,42,'Alta','FLAG_17'
WHERE NOT EXISTS (SELECT 1 FROM afectaciones WHERE event_required='FLAG_17' AND titulo='Contingencia por indisponibilidad de monitoreo remoto');
INSERT INTO afectaciones (titulo,tipo,estado,municipio,sector,descripcion,inicio,fin_estimado,cuentas_estimadas,x_pct,y_pct,prioridad,event_required)
SELECT 'Operación manual de estaciones prioritarias','Continuidad operacional','En curso','Saint Louis','Sector Norte','Se activó verificación manual de variables y maniobras locales en instalaciones prioritarias.','2026-09-23 12:30:00','2026-09-23 19:00:00',9120,57,30,'Crítica','FLAG_18'
WHERE NOT EXISTS (SELECT 1 FROM afectaciones WHERE event_required='FLAG_18' AND titulo='Operación manual de estaciones prioritarias');
INSERT INTO afectaciones (titulo,tipo,estado,municipio,sector,descripcion,inicio,fin_estimado,cuentas_estimadas,x_pct,y_pct,prioridad,event_required)
SELECT 'Presión irregular y cierre preventivo de ramal','Contingencia','En atención','Soledade','San Felipe','Se aisló preventivamente un ramal tras registrarse transitorios de presión fuera del patrón esperado.','2026-09-23 14:20:00','2026-09-23 21:30:00',11700,73,51,'Crítica','FLAG_19'
WHERE NOT EXISTS (SELECT 1 FROM afectaciones WHERE event_required='FLAG_19' AND titulo='Presión irregular y cierre preventivo de ramal');
INSERT INTO afectaciones (titulo,tipo,estado,municipio,sector,descripcion,inicio,fin_estimado,cuentas_estimadas,x_pct,y_pct,prioridad,event_required)
SELECT 'Emergencia hidráulica en corredor norte','Emergencia','En atención','Saint Louis','Corredor Norte','Ruptura de conducción, anegamiento vial y caída abrupta de presión. Protección civil y servicios médicos trabajan en la zona.','2026-09-23 16:42:00',NULL,18600,61,18,'Crítica','FLAG_20'
WHERE NOT EXISTS (SELECT 1 FROM afectaciones WHERE event_required='FLAG_20' AND titulo='Emergencia hidráulica en corredor norte');

-- Memes, burlas y presión social escalonada.
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption)
SELECT 1,'FLAG_16',0,'@memes_del_tinaco','Memes del Tinaco','Saint Louis','Humor','Cuando INTERAFAS dice “operación normal” pero tu regadera ya suena como cafetera.',648,291,NULL,'OPERACIÓN NORMAL','El tinaco: “yo no firmé para esto” 💀'
WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@memes_del_tinaco' AND event_required='FLAG_16');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption)
SELECT 2,'FLAG_17',0,'@ctrl_alt_agua','Ctrl+Alt+Agua','Metropolitano','Humor','Ya salió el comunicado de “incidente tecnológico”. Internet haciendo su trabajo:',1090,602,NULL,'HAVE YOU TRIED TURNING THE CITY OFF AND ON AGAIN?','— Soporte técnico metropolitano, probablemente.'
WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@ctrl_alt_agua' AND event_required='FLAG_17');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption)
SELECT 3,'FLAG_18',0,'@scada_memes','SCADA Memes','Metropolitano','Humor','Operadores verificando en campo porque ya nadie le cree a la pantalla:',1650,877,NULL,'CONFÍA EN MÍ BRO','La pantalla: 100% normal · La planta: 🔥'
WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@scada_memes' AND event_required='FLAG_18');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption)
SELECT 3,'FLAG_19',0,'@licitacion_memes','Licitación Memes','Soledade','Humor','Cuando empiezan a revisar contratos y de pronto todos ponen “fuera de oficina”.',2310,1205,NULL,'VISTO A LAS 14:18','Contratista abandonó el grupo.'
WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@licitacion_memes' AND event_required='FLAG_19');
INSERT INTO scenario_social_posts (phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party,meme_title,meme_caption)
SELECT 4,'FLAG_20',0,'@ciudad_sin_filtro','Ciudad Sin Filtro','Metropolitano','Humor negro','Ya no sé si abrir Pulso Metropolitano o Protección Civil. Cada refresh desbloquea otro desastre.',3880,2490,NULL,'NUEVO LOGRO DESBLOQUEADO','“Infraestructura crítica: modo pesadilla”'
WHERE NOT EXISTS (SELECT 1 FROM scenario_social_posts WHERE handle='@ciudad_sin_filtro' AND event_required='FLAG_20');

-- El defacement solo existe al acreditar las 20 banderas.
UPDATE news_articles SET event_required='ALL_FLAGS', phase_required=4 WHERE slug='defacement-interafas-colectivo-umbral';
UPDATE news_articles SET headline='Hacktivistas crean una pestaña clandestina dentro del portal de INTERAFAS', subheadline='Tras completarse la cadena de intrusión, aparece una nueva sección // SYSTEM // con un mensaje atribuido a Colectivo Umbral.', body='Una nueva pestaña apareció dentro de la navegación de INTERAFAS después de que la investigación del incidente alcanzara su punto más crítico. A diferencia de un derribo total del sitio, el contenido institucional continúa disponible, pero la sección // SYSTEM // muestra un mensaje atribuido al colectivo ficticio Umbral.\n\nLa intervención visual afirma que la institución acumuló deuda técnica, controles rotos y una confianza excesiva en su arquitectura. La presencia de la pestaña sugiere que el atacante consiguió persistir o modificar componentes de presentación del portal sin necesidad de sustituir toda la web.\n\nEspecialistas consultados señalaron que este tipo de alteración debe tratarse como evidencia: retirar el contenido de inmediato puede destruir información útil para reconstruir la ruta de acceso. El equipo de respuesta tendría que preservar archivos, registros, marcas de tiempo y cambios de configuración antes de restaurar una versión confiable.\n\nLa directora de Tecnologías, Laura Bianchi Romero, indicó que la aparición del mensaje se integró a la investigación forense y que el organismo mantuvo el resto del portal disponible mientras aislaba el componente afectado.\n\nLa publicación generó nuevas críticas y burlas en redes sociales, pero también elevó la presión para que la investigación determine si la alteración fue obra del mismo actor responsable del resto de la intrusión.\n\nPulso Metropolitano verificó que la pestaña únicamente aparece después de completarse la cadena de hallazgos del incidente.' WHERE slug='defacement-interafas-colectivo-umbral';
UPDATE scenario_social_posts SET event_required='ALL_FLAGS', content='Apareció una pestaña // SYSTEM // dentro de INTERAFAS con un mensaje del Colectivo Umbral. El resto del portal sigue arriba, pero la captura ya está en todas partes.' WHERE handle='@captura_urbana';

-- Cobertura metropolitana no relacionada: mantiene vivo el portal antes y durante la crisis.
INSERT IGNORE INTO news_articles (phase_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking) VALUES
(0,0,'local','parque-lineal-rio-abre-tramo','Abre nuevo tramo del parque lineal del Río Verde','El corredor suma ciclovía, iluminación y áreas de descanso entre Saint Louis y Soledade.','El nuevo tramo del parque lineal del Río Verde abrió al público este miércoles con 3.4 kilómetros adicionales de ciclovía, andadores y áreas de descanso. Autoridades metropolitanas estiman que el corredor podrá recibir hasta 12 mil usuarios durante los fines de semana.\n\nLa obra incluye iluminación de bajo consumo, zonas de sombra y puntos de hidratación. Vecinos de colonias cercanas celebraron la recuperación del espacio, aunque pidieron reforzar seguridad y mantenimiento nocturno.\n\nEl proyecto forma parte de un programa de movilidad activa que conectará parques, centros educativos y estaciones de transporte. La siguiente etapa contempla dos puentes peatonales.\n\nOrganizaciones ciclistas señalaron que la infraestructura será útil si se mantiene libre de vehículos y comercio invasivo. El municipio anunció vigilancia y limpieza diaria durante el primer mes.','Daniela Ruiz · Ciudad','infrastructure-map.svg',15,0,0),
(0,0,'comunidad','universidad-robotica-final-nacional','Equipo universitario llega a final nacional de robótica','Estudiantes metropolitanos competirán con un robot autónomo diseñado para tareas de rescate.','Un equipo de estudiantes de ingeniería obtuvo su pase a la final nacional de robótica con un prototipo autónomo capaz de identificar obstáculos, transportar pequeños suministros y enviar telemetría a un centro de control.\n\nEl proyecto fue desarrollado durante seis meses y combina visión artificial, navegación autónoma y sensores de proximidad. Los integrantes explicaron que el objetivo no es sustituir a brigadistas, sino explorar herramientas para entornos inseguros.\n\nLa universidad informó que apoyará el viaje del equipo y abrirá una demostración pública antes de la competencia. Docentes destacaron que el prototipo integra conocimientos de electrónica, programación y diseño mecánico.\n\nLa final se realizará el próximo mes y reunirá a 24 instituciones del país.','Mateo Cruz · Educación','operations-room.svg',14,0,0),
(0,0,'local','ruta-nocturna-transporte-prueba','Transporte metropolitano probará ruta nocturna durante cuatro fines de semana','El servicio piloto conectará Centro Histórico, zona universitaria y corredor hospitalario.','La autoridad de movilidad anunció una prueba de transporte nocturno durante cuatro fines de semana. La ruta operará de 23:00 a 03:00 horas y conectará zonas con actividad cultural, estudiantil y hospitalaria.\n\nEl programa busca medir demanda, tiempos de viaje y percepción de seguridad antes de decidir si se convierte en servicio permanente. Las unidades tendrán seguimiento GPS y paradas definidas.\n\nComerciantes y trabajadores nocturnos recibieron positivamente el anuncio, mientras asociaciones vecinales solicitaron vigilancia en los puntos de ascenso y descenso.\n\nLa autoridad publicará un reporte de uso al concluir la prueba.','Sergio Vidal · Movilidad','support-team.svg',13,0,0),
(0,0,'cultura','festival-luces-centro-historico','Festival de luces transformará ocho fachadas del Centro Histórico','Proyecciones, música y recorridos peatonales se realizarán durante tres noches.','Ocho edificios del Centro Histórico formarán parte de un festival de iluminación arquitectónica que combinará proyecciones, música y recorridos peatonales. La programación incluirá funciones cada media hora.\n\nLos organizadores informaron que el acceso será gratuito y que varias calles tendrán cierres parciales desde las 18:00 horas. También habrá presentaciones de artistas locales y un corredor gastronómico.\n\nProtección Civil recomendó utilizar transporte público y atender la señalización temporal. Comerciantes esperan un aumento de visitantes durante el fin de semana.\n\nEl programa completo estará disponible en módulos turísticos y redes oficiales.','Clara Ibarra · Cultura','hero-water.svg',12,0,0),
(0,0,'comunidad','refugios-adopcion-mascotas-jornada','Refugios preparan jornada metropolitana de adopción responsable','Más de 80 perros y gatos participarán en una campaña conjunta de salud y adopción.','Refugios y asociaciones civiles realizarán una jornada de adopción responsable con más de 80 animales previamente valorados por equipos veterinarios.\n\nLa actividad incluirá vacunación, orientación sobre esterilización y registro de tutores. Las organizaciones pedirán identificación y una entrevista breve antes de autorizar cada adopción.\n\nVeterinarios participantes recordaron que adoptar implica gastos permanentes de alimentación, salud y cuidados. También pidieron evitar regalos impulsivos de animales.\n\nLa jornada se realizará el sábado en la plaza metropolitana.','Ana Lucía Mora · Comunidad','support-team.svg',11,0,0),
(0,0,'economia','mercado-productores-regionales','Productores regionales abren mercado temporal en Soledade','Cuarenta cooperativas ofrecerán alimentos, textiles y productos artesanales sin intermediarios.','Cuarenta cooperativas de la región instalarán un mercado temporal en Soledade durante tres días. La iniciativa busca conectar directamente a productores con consumidores y reducir costos de intermediación.\n\nLa oferta incluye frutas, hortalizas, quesos, panadería, textiles y productos artesanales. La organización habilitará pagos electrónicos y espacios de degustación.\n\nProductores señalaron que este tipo de mercados ayuda a probar nuevos productos y conocer directamente las preferencias de los compradores.\n\nEl municipio prevé replicar el modelo una vez al mes si la asistencia supera las expectativas.','Raúl Montenegro · Economía','payment-online.svg',10,0,0),
(0,0,'local','biblioteca-amplia-horarios-examenes','Biblioteca Metropolitana amplía horarios por temporada de exámenes','Las salas de estudio permanecerán abiertas hasta medianoche durante tres semanas.','La Biblioteca Metropolitana ampliará temporalmente sus horarios para atender a estudiantes durante la temporada de exámenes. Las salas principales operarán hasta las 00:00 horas de lunes a sábado.\n\nLa institución habilitará 180 espacios adicionales de estudio, préstamo de computadoras y asesorías breves para búsqueda bibliográfica.\n\nEl acceso nocturno requerirá registro en recepción y las áreas infantiles conservarán su horario habitual.\n\nLa medida será evaluada con base en afluencia y uso de servicios digitales.','Paula León · Ciudad','support-team.svg',9,0,0),
(0,0,'comunidad','bomberos-rescatan-perro-canal','Bomberos rescatan a un perro atrapado en canal pluvial','El animal fue entregado a una asociación y se encuentra fuera de peligro.','Bomberos metropolitanos rescataron a un perro que quedó atrapado en un canal pluvial después de una lluvia ligera. Vecinos alertaron a los servicios de emergencia al escuchar al animal.\n\nLa maniobra requirió cuerdas y una escalera para descender de forma segura. El perro presentaba signos de agotamiento, pero no lesiones graves.\n\nUna asociación local lo trasladó a valoración veterinaria y comenzó la búsqueda de sus tutores.\n\nEl cuerpo de bomberos aprovechó el caso para pedir a la población no ingresar a canales durante lluvias y reportar animales atrapados a números de emergencia.','Lucía Prado · Comunidad','field-engineer.svg',8,0,0);
