ALTER TABLE news_articles ADD COLUMN IF NOT EXISTS event_required VARCHAR(100) NULL AFTER phase_required;
ALTER TABLE scenario_social_posts ADD COLUMN IF NOT EXISTS event_required VARCHAR(100) NULL AFTER phase_required;
CREATE INDEX IF NOT EXISTS idx_news_event_required ON news_articles(event_required);
CREATE INDEX IF NOT EXISTS idx_social_event_required ON scenario_social_posts(event_required);

-- Diversidad visual para el archivo ya existente.
UPDATE news_articles SET hero_asset = CASE MOD(id,13)
  WHEN 0 THEN 'photo-pumping'
  WHEN 1 THEN 'photo-reservoir'
  WHEN 2 THEN 'photo-scada'
  WHEN 3 THEN 'photo-control'
  WHEN 4 THEN 'photo-tanker'
  WHEN 5 THEN 'photo-break'
  WHEN 6 THEN 'photo-distribution'
  WHEN 7 THEN 'photo-cyber'
  WHEN 8 THEN 'photo-ambulance'
  WHEN 9 THEN 'photo-evidence'
  WHEN 10 THEN 'photo-flood'
  WHEN 11 THEN 'photo-microphone'
  ELSE 'photo-press' END;

-- FLAG 16: primera presión pública + voz operativa.
INSERT IGNORE INTO news_articles
(phase_required,event_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking)
VALUES
(1,'FLAG_16',0,'servicios','operacion-hidraulica-explica-baja-presion','Operación Hidráulica reconoce anomalías: “No estamos ante una falla ordinaria”','Elena Marín Soler, directora de Operación Hidráulica, confirma variaciones atípicas y despliegue de cuadrillas en el corredor norte.',
'La primera explicación técnica de INTERAFAS llegó después de que decenas de usuarios reportaran baja presión casi al mismo tiempo en sectores que normalmente no comparten una misma incidencia. La directora de Operación Hidráulica, Elena Marín Soler, confirmó que el patrón obligó a ampliar la revisión más allá de una avería convencional.\n\n“Hay comportamientos que no corresponden a una fuga aislada ni a un mantenimiento programado. Estamos verificando bombeo, niveles de tanque y telemetría de manera simultánea”, señaló Marín Soler en entrevista con Pulso Metropolitano.\n\nLa funcionaria indicó que las cuadrillas recibieron instrucciones de validar físicamente estaciones y válvulas críticas, incluso cuando el centro de monitoreo todavía mostraba variables dentro de rangos aparentemente aceptables. Esa discrepancia es uno de los puntos que más preocupa al equipo operativo.\n\nPreguntada sobre si existía riesgo de desabasto, respondió que el sistema mantenía reservas, pero evitó garantizar que la presión pudiera sostenerse sin nuevas maniobras. “No sería responsable prometer normalidad mientras seguimos descartando escenarios”, dijo.\n\nINTERAFAS pidió a los usuarios de las zonas afectadas moderar temporalmente consumos no esenciales y consultar el mapa de afectaciones. La institución no ha informado todavía una causa definitiva.',
'Mariana Solís · Unidad de Investigación','elena-marin.svg',96,0,1);

-- FLAG 17: confirmación tecnológica + entrevista con TI.
INSERT IGNORE INTO news_articles
(phase_required,event_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking)
VALUES
(2,'FLAG_17',0,'ultima','tecnologias-admite-acceso-no-previsto','Tecnologías admite actividad no prevista en sistemas internos; “el alcance aún no está cerrado”','Laura Bianchi Romero confirma que el incidente dejó de tratarse como una simple indisponibilidad del portal.',
'INTERAFAS confirmó que la investigación interna detectó actividad no prevista en sistemas que no deberían haber sido alcanzados desde el entorno público. La directora de Tecnologías e Innovación, Laura Bianchi Romero, dijo que el organismo activó procedimientos de contención y preservación de evidencia.\n\n“En este momento no podemos sostener que se trate solamente de una falla de disponibilidad. Hay indicadores suficientes para analizar un acceso no autorizado”, afirmó Bianchi Romero en una entrevista realizada fuera del centro de operaciones.\n\nLa directiva evitó precisar qué credenciales o aplicaciones pudieron verse comprometidas, argumentando que divulgar detalles antes de terminar la contención podría afectar la investigación. Sí confirmó que se revocaron sesiones, se restringieron conexiones internas y se reforzó el monitoreo.\n\nPulso Metropolitano preguntó por qué algunos reportes de presión coincidieron con la degradación de los servicios digitales. Bianchi respondió que no existe todavía una atribución técnica concluyente, pero reconoció que la coincidencia “es parte central de la hipótesis de trabajo”.\n\nLa institución mantiene activos canales alternos de atención mientras especialistas revisan registros de acceso, cambios de configuración y movimientos entre sistemas.',
'Iván Rojas · Tecnología','laura-bianchi.svg',110,0,1);

-- FLAG 18: entorno operacional + director general e Isabelle Laurent.
INSERT IGNORE INTO news_articles
(phase_required,event_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking)
VALUES
(3,'FLAG_18',0,'ultima','interafas-reconoce-alcance-operacional','INTERAFAS reconoce que la investigación alcanzó sistemas de supervisión operacional','Adrián Leclerc e Isabelle Laurent confirman verificaciones manuales y restricciones temporales en el centro de control.',
'El incidente tecnológico que comenzó con intermitencias digitales escaló a una revisión de sistemas vinculados con la supervisión operacional del servicio de agua. El director general de INTERAFAS, Adrián Leclerc Mendoza, confirmó que el organismo trabaja bajo un esquema de contingencia reforzada.\n\n“No vamos a minimizar el escenario. Si existe una duda sobre la integridad de una señal, la instrucción es contrastarla en campo antes de ejecutar decisiones”, declaró Leclerc.\n\nLa coordinadora de Monitoreo Operacional, Isabelle Laurent Castro, explicó que varios equipos pasaron a validación manual. “Lo importante es separar lo que vemos en pantalla de lo que realmente está ocurriendo en la infraestructura. Esa verificación física está en curso”, dijo.\n\nLaurent evitó señalar si ya se había identificado una manipulación de variables, aunque confirmó que se revisan historiales de bombas, presión y caudal. Personal operativo fue desplegado a instalaciones consideradas prioritarias.\n\nEl director general rechazó responder si alguien dentro de INTERAFAS ignoró alertas previas. “Esa pregunta tendrá que responderse con evidencia, no con especulación. Pero si hubo omisiones, tendrán que documentarse”, afirmó.\n\nLa contingencia ya tiene efectos administrativos: cambios de turno, suspensión de mantenimientos no esenciales y presencia de personal jurídico y tecnológico en el centro de coordinación.',
'Carla Méndez · Enviada especial','adrian-leclerc.svg',118,0,1);

-- FLAG 19: presión política, entrevista al alcalde y denuncia financiera.
INSERT IGNORE INTO news_articles
(phase_required,event_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking)
VALUES
(3,'FLAG_19',0,'politica','alcalde-al-limite-entrevista-interafas','“No me diga que nadie lo vio”: alcalde enfrenta preguntas por la crisis de INTERAFAS','En una entrevista tensa, el alcalde de Saint Louis exige nombres, tiempos y responsabilidades mientras el incidente sigue abierto.',
'El alcalde de Saint Louis, Mateo Rivas Calderón, llegó a la conferencia de coordinación con un mensaje de respaldo institucional, pero terminó enfrentando preguntas sobre controles, contratos y advertencias previas.\n\n—¿Quién falló? —preguntó Pulso Metropolitano.\n\n“Eso lo va a determinar la investigación”, respondió. Al insistir sobre si el gobierno municipal conocía debilidades de seguridad, el alcalde elevó el tono: “No me diga que nadie lo vio. Si había reportes y alguien decidió archivarlos, quiero saber quién fue”.\n\nRivas Calderón reconoció que recibió un informe preliminar que menciona controles de acceso, sistemas internos y la necesidad de revisar proveedores tecnológicos. Negó que su oficina hubiera autorizado ocultar información sobre el incidente.\n\n—¿Renunciaría algún funcionario si se confirma negligencia?\n\n“Si hubo negligencia grave, no voy a proteger a nadie. Pero tampoco voy a condenar a una persona antes de tener el expediente completo”, contestó.\n\nEl alcalde fue cuestionado también por la contratación de servicios tecnológicos durante los últimos dos años. Señaló que solicitará a la Contraloría un corte extraordinario de expedientes y entregables.\n\nLa entrevista terminó cuando asesores de comunicación dieron por concluida la ronda de preguntas después de que se le preguntara si confiaba todavía en la dirección de INTERAFAS. “Confío en que responda con hechos”, dijo antes de retirarse.',
'Julia Ferrer · Política','photo-microphone',125,0,1),
(3,'FLAG_19',0,'politica','denuncia-contratos-posible-desvio','Denuncia pide investigar contratos tecnológicos y un posible desvío de 12.7 millones','La acusación no acredita por sí sola un desfalco; Contraloría confirma que revisará pagos, entregables y modificaciones contractuales.',
'Una denuncia administrativa presentada ante la Contraloría Metropolitana solicitó revisar contratos de modernización tecnológica vinculados con INTERAFAS y operaciones por 12.7 millones de unidades monetarias que, según los promoventes, requieren aclaración documental.\n\nEl escrito habla de un posible desvío de recursos, pero hasta ahora ninguna autoridad ha determinado que exista un desfalco. La revisión se concentrará en entregables, ampliaciones de contrato, fechas de aceptación y relación entre proveedores.\n\nLa directora Administrativa de INTERAFAS, Sofía Costa Navarro, afirmó que pondrá a disposición expedientes, órdenes de pago y actas de recepción. “Una investigación financiera debe seguir el rastro documental completo; no vamos a adelantar conclusiones”, declaró.\n\nEl director Jurídico, Marc Dubois Hernández, señaló que la institución preservará documentación digital y física relacionada con los procedimientos señalados. Añadió que cualquier alteración posterior a la apertura de la revisión sería tratada como un incidente adicional.\n\nPartidos de oposición ficticios FMC y ACC exigieron una auditoría externa, mientras MRP pidió evitar que la investigación financiera interfiera con la recuperación operativa.\n\nPulso Metropolitano solicitó postura a dos proveedores mencionados en la denuncia. Ambos negaron irregularidades y aseguraron haber cumplido sus contratos.',
'Equipo de Investigación','sofia-costa.svg',121,1,1);

-- FLAG 20: impacto humano, intervención de autoridades, defacement y presión presidencial.
INSERT IGNORE INTO news_articles
(phase_required,event_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking)
VALUES
(4,'FLAG_20',0,'ultima','ruptura-inundacion-heridos-crisis','Ruptura e inundación dejan seis heridos durante la peor hora de la crisis hídrica','Autoridades investigan si una transición abrupta de presión contribuyó a la falla de una conducción; dos personas permanecen hospitalizadas.',
'La crisis de INTERAFAS dejó de ser únicamente tecnológica. Una ruptura en una conducción principal provocó inundación en un paso vial del corredor norte y movilizó a cuerpos de emergencia. Seis personas resultaron lesionadas; dos fueron trasladadas a un hospital para observación.\n\nProtección Civil informó que todavía no existe una relación causal definitiva entre el incidente cibernético y la ruptura. Sin embargo, especialistas analizan si cambios abruptos de presión pudieron aumentar el estrés sobre un tramo previamente identificado como vulnerable.\n\nVecinos describieron un incremento repentino del flujo sobre la vialidad. Equipos de emergencia cerraron el paso mientras operadores de INTERAFAS aislaron el sector mediante maniobras locales.\n\nLa directora de Operación Hidráulica, Elena Marín, confirmó que la secuencia de presión será preservada como evidencia técnica. “Necesitamos reconstruir minuto por minuto lo que ocurrió antes de la ruptura”, señaló.\n\nEl incidente afectó temporalmente accesos a una clínica y obligó a redistribuir camiones cisterna hacia sectores con menor reserva. No se reportan fallecimientos.\n\nLa prioridad inmediata es estabilizar la red y determinar si el daño fue consecuencia directa, indirecta o coincidente con el ataque.',
'Equipo de Última Hora','photo-flood',160,0,1),
(4,'FLAG_20',0,'ultima','investigacion-detenciones-despidos','Investigación escala: un contratista detenido, dos despidos y tres mandos suspendidos','Fiscalía, Contraloría y autoridades administrativas abren expedientes paralelos; INTERAFAS confirma dos despidos y tres suspensiones cautelares.',
'La respuesta institucional entró en una nueva etapa después del colapso operativo. Autoridades confirmaron la detención preventiva de un contratista externo para el cumplimiento de una orden relacionada con preservación de evidencia y accesos a sistemas. La detención no equivale a una declaración de culpabilidad.\n\nINTERAFAS informó además el despido de dos responsables de nivel medio tras una revisión administrativa inicial y la suspensión cautelar de tres mandos mientras se examinan decisiones tomadas antes y durante el incidente. Los despidos son medidas laborales y no equivalen por sí mismos a responsabilidad penal.\n\nEl director Jurídico, Marc Dubois, confirmó que se preparan denuncias por acceso no autorizado, alteración de sistemas y posibles omisiones de control. “Se van a distinguir responsabilidades técnicas, administrativas y, si corresponde, penales”, declaró.\n\nLa Contraloría solicitó imágenes de servidores, registros de autenticación, expedientes de contratación y comunicaciones de proveedores. Equipos forenses comenzaron a trabajar bajo cadena de custodia.\n\nFuentes cercanas a la investigación señalan que una línea de análisis se concentra en el uso de credenciales y otra en las condiciones bajo las cuales determinados sistemas internos podían ser alcanzados desde componentes expuestos.\n\nLos nombres de las personas investigadas no serán publicados mientras no exista una determinación formal.',
'Unidad de Investigación','photo-evidence',170,0,1),
(4,'FLAG_20',0,'politica','presidencia-exige-investigacion-formal','Presidencia exige investigación formal y un informe completo sobre la crisis de INTERAFAS','El Ejecutivo solicita responsabilidades, cronología del ataque, afectaciones humanas y revisión de contratos vinculados con sistemas críticos.',
'La Presidencia emitió un posicionamiento extraordinario tras conocerse las afectaciones operativas y humanas relacionadas con la crisis de INTERAFAS. El comunicado ordena integrar una investigación formal con participación de instancias técnicas, administrativas y de procuración de justicia.\n\nEl documento exige reconstruir la cronología completa: desde las primeras anomalías digitales hasta el acceso a funciones de supervisión, las variaciones de presión y la afectación física registrada en el corredor norte.\n\nTambién solicita revisar la actuación de funcionarios, proveedores y responsables de continuidad operativa. La instrucción incluye entregar un informe sobre contratos tecnológicos, controles de acceso y recomendaciones que hubieran quedado pendientes.\n\nEn una breve declaración ante medios, una vocería presidencial señaló que “la infraestructura crítica no admite explicaciones incompletas cuando existen consecuencias para la población”.\n\nLa Presidencia pidió que los hallazgos no clasificados sean publicados una vez asegurada la evidencia, y que se establezca un calendario de medidas correctivas verificables.\n\nEl posicionamiento incrementa la presión sobre los gobiernos municipales y sobre la dirección general de INTERAFAS, que hasta ahora había concentrado la comunicación institucional.',
'Redacción Política','photo-press',180,0,1),
(4,'FLAG_20',0,'ultima','defacement-interafas-colectivo-umbral','Portal de INTERAFAS es reemplazado por mensaje de un colectivo hacktivista','La página institucional dejó de mostrar servicios y apareció una pantalla con la frase “el gobierno no sirve”.',
'El portal público de INTERAFAS dejó de mostrar su contenido institucional y fue sustituido por una pantalla atribuida a un grupo que se identifica como Colectivo Umbral. El mensaje afirma que “el gobierno no sirve” y reivindica la intrusión como una demostración de debilidad institucional.\n\nPulso Metropolitano verificó que la alteración visual, conocida como defacement, afecta el acceso normal a la portada y a diferentes secciones públicas del organismo dentro de la ventana actual del incidente.\n\nEspecialistas consultados advierten que un defacement no prueba por sí mismo que el atacante conserve control sobre sistemas operacionales; sin embargo, en el contexto de la crisis amplifica el impacto reputacional y obliga a tratar el servidor web como evidencia.\n\nLa directora de Tecnologías, Laura Bianchi, señaló que el portal permanecerá aislado mientras se determine la ruta de modificación. “La prioridad no es volver a poner una portada en línea; es asegurar que entendemos cómo ocurrió”, indicó.\n\nEl ataque fue ampliamente compartido en redes, donde capturas del mensaje circularon junto con críticas a la gestión del incidente. INTERAFAS pidió no utilizar enlaces alternativos o supuestos sitios de recuperación difundidos por cuentas no verificadas.\n\nLa investigación busca establecer si la alteración del portal fue realizada por el mismo actor que intervino en etapas anteriores o por un grupo oportunista que aprovechó la exposición pública del incidente.',
'Lucía Andrade · Ciberseguridad','photo-cyber',175,0,1),
(4,'FLAG_20',0,'comunidad','hospitales-reservas-y-riesgo-sanitario','Hospitales activan reservas y protocolo sanitario por caída de presión','La red hospitalaria mantuvo servicios esenciales, pero advirtió que una interrupción prolongada habría obligado a suspender procedimientos no urgentes.',
'Tres hospitales y varias unidades de atención primaria activaron reservas internas de agua durante el periodo de menor presión. Las autoridades sanitarias informaron que los servicios esenciales continuaron operando, aunque algunos procedimientos no urgentes fueron reprogramados de manera preventiva.\n\nAdministradores hospitalarios explicaron que la presión reducida puede afectar esterilización, limpieza y sistemas auxiliares si las reservas se agotan. Por esa razón se coordinó suministro preventivo mediante cisternas.\n\nNo se ha identificado contaminación de la red, pero personal sanitario solicitó mantener vigilancia sobre parámetros de calidad después de cambios bruscos de presión.\n\nLa situación expone uno de los riesgos menos visibles de una brecha en infraestructura hidráulica: una alteración digital puede convertirse rápidamente en un problema de continuidad clínica, movilidad urbana y protección civil.\n\nINTERAFAS informó que la recuperación de presión será gradual para evitar nuevos transitorios en la red.',
'Andrea Vega · Comunidad','photo-ambulance',150,1,1);

-- Recuperación: consecuencias institucionales posteriores.
INSERT IGNORE INTO news_articles
(phase_required,event_required,delay_seconds,category,slug,headline,subheadline,body,author,hero_asset,priority,display_order,breaking)
VALUES
(5,'RECOVERY_STARTED',0,'politica','director-general-comparecera','Director general de INTERAFAS comparecerá ante comisión especial','Adrián Leclerc deberá responder sobre controles, advertencias previas, contratación y decisiones tomadas durante la emergencia.',
'Una comisión especial convocó al director general de INTERAFAS, Adrián Leclerc Mendoza, para explicar la gestión del incidente y las decisiones tomadas antes, durante y después de la contingencia.\n\nLa comparecencia incluirá preguntas sobre segmentación de sistemas, controles de acceso, supervisión de proveedores, continuidad operativa y mecanismos de respuesta a incidentes.\n\nLeclerc confirmó que acudirá y aseguró que entregará la cronología interna disponible. “Una crisis de esta naturaleza exige rendición de cuentas y evidencia verificable”, declaró.\n\nLa comisión también convocará a responsables de Operación Hidráulica, Tecnologías, Administración y Monitoreo Operacional.\n\nLa oposición anunció que solicitará información sobre observaciones de auditorías anteriores, mientras el bloque gubernamental pidió separar las fallas comprobadas de acusaciones todavía no acreditadas.',
'Redacción Política','adrian-leclerc.svg',115,0,0);

-- Redes: presión creciente y reacción inmediata por eventos.
INSERT IGNORE INTO scenario_social_posts
(phase_required,event_required,delay_seconds,handle,display_name,municipality,label,content,likes,shares,party)
VALUES
(1,'FLAG_16',0,'@agua_norte_ya','Vecinos del Norte','Saint Louis','Servicio','Ya no es una colonia: somos varios sectores con la misma baja presión. Que dejen de decir que es mantenimiento y expliquen qué está pasando.',286,104,NULL),
(2,'FLAG_17',0,'@cuentasclaras','Cuentas Claras Metro','Metropolitano','Crítica','Si ya admiten acceso no autorizado, queremos saber desde cuándo lo sabían y quién decidió seguir operando como si nada. Esto huele muy mal.',421,188,NULL),
(3,'FLAG_18',0,'@operador_enojado','Operador Anónimo','Metropolitano','Crítica','Si están verificando TODO a mano es porque ya no confían en lo que ven en pantalla. Eso no es una “intermitencia”, eso es una crisis.',598,271,NULL),
(3,'FLAG_19',0,'@basta_de_excusas','Basta de Excusas','Soledade','Crítica','¿Contratos dudosos, sistemas expuestos y ahora nadie sabe quién autorizó qué? Ya estuvo bueno de hacerse p#$%s. Queremos responsables, no comunicados.',811,396,NULL),
(3,'FLAG_19',0,'@fmc_metropolitano','FMC Metropolitano','Metropolitano','Política','Solicitamos auditoría independiente, comparecencias públicas y preservación inmediata de todos los contratos y correos vinculados con la modernización tecnológica.',403,174,'FMC'),
(4,'FLAG_20',0,'@corredor_norte','Alerta Corredor Norte','Saint Louis','Emergencia','Hay agua cubriendo la vialidad y ambulancias entrando. Esto ya dejó de ser un problema de computadoras. ¿Quién va a responder por los heridos?',1290,811,NULL),
(4,'FLAG_20',0,'@no_fue_una_falla','No Fue Una Falla','Metropolitano','Crítica','Nos dijeron que todo estaba “bajo control” hasta que literalmente se rompió la red. Que no salgan mañana con otro comunicado de m#$%.',1552,932,NULL),
(4,'FLAG_20',0,'@presion_ciudadana','Presión Ciudadana','Cerro de San Pablo','Política','Presidencia ya pidió investigación formal. Ahora queremos nombres, fechas, contratos, bitácoras y sanciones. Todo público.',909,421,NULL),
(4,'FLAG_20',0,'@captura_urbana','Captura Urbana','Metropolitano','Última hora','La web de INTERAFAS fue reemplazada por un mensaje hacktivista. La captura ya circula por todas partes. El golpe reputacional es brutal.',1820,1170,NULL);
