<?php
require __DIR__.'/includes/scenario.php';$pdo=db();$municipio=trim($_GET['municipio']??'');$estado=trim($_GET['estado']??'');
$ctx=lab_attempt_context_any(); $attemptId=$ctx?(int)$ctx['attempt_id']:0;
$sql="SELECT a.* FROM afectaciones a WHERE (a.event_required IS NULL OR EXISTS (SELECT 1 FROM scenario_events se WHERE se.event_code=a.event_required".($attemptId?" AND se.attempt_id=?":"")."))";$params=[]; if($attemptId)$params[]=$attemptId;if($municipio!==''){$sql.=' AND municipio=?';$params[]=$municipio;}if($estado!==''){$sql.=' AND estado=?';$params[]=$estado;}$sql.=" ORDER BY FIELD(estado,'En atención','En curso','Monitoreo','Programada','Concluida'), prioridad DESC, inicio ASC";$q=$pdo->prepare($sql);$q->execute($params);$items=$q->fetchAll();
$pageTitle='Mapa de afectaciones';include __DIR__.'/includes/header.php';
?>
<section class="impact-hero"><div class="wrap"><div class="eyebrow">Estado del servicio</div><h1>Mapa de afectaciones y trabajos programados</h1><p>Consulta mantenimientos, fugas, obras y variaciones operativas reportadas en la zona metropolitana.</p></div></section>
<section class="section"><div class="wrap"><form class="impact-filters" method="get"><div class="field"><label>Municipio</label><select name="municipio"><option value="">Todos</option><?php foreach(['Cerro de San Pablo','Saint Louis','Soledade'] as $m): ?><option <?= $municipio===$m?'selected':'' ?>><?= htmlspecialchars($m) ?></option><?php endforeach; ?></select></div><div class="field"><label>Estado</label><select name="estado"><option value="">Todos</option><?php foreach(['En atención','En curso','Monitoreo','Programada','Concluida'] as $e): ?><option <?= $estado===$e?'selected':'' ?>><?= htmlspecialchars($e) ?></option><?php endforeach; ?></select></div><button class="btn">Aplicar</button><a class="btn btn-outline" href="/afectaciones.php">Limpiar</a></form><div class="impact-layout section-spacer"><div class="impact-map"><img src="/assets/img/metro-map-v2.svg" alt="Mapa esquemático metropolitano"><?php foreach($items as $i): ?><a class="impact-pin <?= strtolower(str_replace([' ','ó'],['-','o'],$i['estado'])) ?>" style="left:<?= (float)$i['x_pct'] ?>%;top:<?= (float)$i['y_pct'] ?>%" href="#impact-<?= $i['id'] ?>" title="<?= htmlspecialchars($i['titulo']) ?>"><span></span></a><?php endforeach; ?><div class="map-legend"><span><i class="pin-red"></i>En atención / curso</span><span><i class="pin-amber"></i>Programada / monitoreo</span><span><i class="pin-green"></i>Concluida</span></div></div><div class="impact-summary"><div><small>Afectaciones mostradas</small><b><?= count($items) ?></b></div><div><small>Actualización</small><b><?= date('d/m/Y H:i') ?></b></div><p>Los puntos son una representación esquemática de los sectores operativos.</p></div></div><div class="impact-list section-spacer"><?php foreach($items as $i): ?><article id="impact-<?= $i['id'] ?>"><div class="impact-state"><span><?= htmlspecialchars($i['estado']) ?></span><small><?= htmlspecialchars($i['prioridad']) ?></small></div><div><small><?= htmlspecialchars($i['tipo'].' · '.$i['municipio'].' · '.$i['sector']) ?></small><h3><?= htmlspecialchars($i['titulo']) ?></h3><p><?= htmlspecialchars($i['descripcion']) ?></p><div class="impact-meta"><span>Inicio: <?= htmlspecialchars(substr($i['inicio'],0,16)) ?></span><?php if($i['fin_estimado']): ?><span>Estimado: <?= htmlspecialchars(substr($i['fin_estimado'],0,16)) ?></span><?php endif; ?><?php if($i['cuentas_estimadas']): ?><span><?= number_format((int)$i['cuentas_estimadas']) ?> cuentas estimadas</span><?php endif; ?></div></div></article><?php endforeach; ?></div></div></section>
<script>window.INTERAFAS_SCENARIO_POLL=true;</script>
<?php include __DIR__.'/includes/footer.php'; ?>
