<?php
require __DIR__.'/includes/config.php'; lab_sensitive_page('facturacion.php','Facturación'); if(empty($_SESSION['user'])){header('Location:/login.php');exit;}
$pdo=db();
$uid=(int)$_SESSION['user']['id'];$q=$pdo->prepare('SELECT * FROM cuentas_servicio WHERE usuario_id=? ORDER BY id');$q->execute([$uid]);$services=$q->fetchAll();$requested=(int)($_GET['cuenta']??0);$c=null;foreach($services as $svc){if(($requested&&$requested===(int)$svc['id'])||(!$requested&&!$c))$c=$svc;}
$facturas=[];$pagos=[];$consumos=[];
if($c){
 $q=$pdo->prepare('SELECT * FROM facturas WHERE cuenta_id=? ORDER BY fecha_emision DESC');$q->execute([$c['id']]);$facturas=$q->fetchAll();
 $q=$pdo->prepare('SELECT p.*,f.folio factura_folio FROM pagos p LEFT JOIN facturas f ON f.id=p.factura_id WHERE p.cuenta_id=? ORDER BY p.creado DESC');$q->execute([$c['id']]);$pagos=$q->fetchAll();
 $q=$pdo->prepare('SELECT * FROM consumos WHERE cuenta_id=? ORDER BY periodo ASC');$q->execute([$c['id']]);$consumos=$q->fetchAll();
}
$pageTitle='Facturación e historial';include __DIR__.'/includes/header.php'; ?>
<section class="section account-section"><div class="wrap"><div class="account-welcome"><div><div class="eyebrow">Mi Portal</div><h1>Facturación e historial</h1><p>Consulta tus recibos, consumo y pagos registrados.</p></div><?php if($c): ?><a class="btn" href="/pago.php?cuenta=<?= $c?($c['id']):0 ?>">Pagar servicio</a><?php endif; ?></div>
<div class="account-layout"><aside class="account-sidebar"><a href="/panel.php">Resumen</a><a href="/mis-servicios.php">Mis servicios</a><a href="/lectura-medidor.php">Lectura del medidor</a><a href="/expediente.php">Mi expediente</a><a class="active" href="/facturacion.php">Facturación</a><a href="/documentos.php">Documentos</a><a href="/afectaciones.php">Mapa de afectaciones</a><a href="/perfil.php">Perfil</a><a href="/vincular-servicio.php">Vincular servicio</a><a class="logout-link" href="/logout.php">Cerrar sesión</a></aside><div>
<?php if(count($services)>1): ?><form class="service-switcher" method="get"><label>Servicio consultado</label><select name="cuenta" onchange="this.form.submit()"><?php foreach($services as $svc): ?><option value="<?= $svc['id'] ?>" <?= $c&&$svc['id']==$c['id']?'selected':'' ?>><?= htmlspecialchars(($svc['alias']?:$svc['cuenta']).' · '.$svc['cuenta']) ?></option><?php endforeach; ?></select></form><?php endif; ?><?php if(!$c): ?><div class="empty-state"><span>＋</span><h2>Aún no tienes un servicio vinculado</h2><p>Vincula tu número de cuenta para consultar recibos, consumos y pagos.</p><a class="btn" href="/vincular-servicio.php">Vincular servicio</a></div><?php else: ?>
<div class="billing-summary"><div><small>Cuenta</small><b><?= htmlspecialchars($c['cuenta']) ?></b><span><?= htmlspecialchars($c['domicilio']) ?></span></div><div><small>Saldo actual</small><b>$<?= number_format((float)$c['saldo'],2) ?></b><span><?= htmlspecialchars($c['estatus']) ?></span></div><div><small>Última lectura</small><b><?= number_format((float)$c['lectura_actual'],1) ?></b><span><?= htmlspecialchars($c['fecha_lectura']) ?></span></div></div>
<?php if($consumos): $max=max(array_column($consumos,'consumo_m3')); ?><div class="consumption-card section-spacer"><div><div class="eyebrow">Consumo</div><h2>Últimos seis periodos</h2><p>Compara tu consumo con el promedio de la zona.</p></div><div class="consumption-bars"><?php foreach($consumos as $co): $w=max(18,round(($co['consumo_m3']/$max)*100)); ?><a href="/facturacion.php?cuenta=<?= $c['id'] ?>#facturas" title="<?= htmlspecialchars($co['periodo']) ?>: <?= $co['consumo_m3'] ?> m³"><i style="height:<?= $w ?>%"></i><b><?= number_format((float)$co['consumo_m3'],1) ?></b><span><?= htmlspecialchars(substr($co['periodo'],5,2)) ?></span></a><?php endforeach; ?></div></div><?php endif; ?>
<div class="section-spacer" id="facturas"><div class="section-heading"><div><div class="eyebrow">Recibos</div><h2>Historial de facturas</h2></div></div><div class="invoice-list"><?php foreach($facturas as $f): ?><a href="/factura.php?id=<?= $f['id'] ?>"><div><small><?= htmlspecialchars($f['periodo']) ?></small><h3><?= htmlspecialchars($f['folio']) ?></h3><p><?= number_format((float)$f['consumo_m3'],1) ?> m³ · vence <?= htmlspecialchars($f['fecha_limite']) ?></p></div><div><span class="invoice-status <?= strtolower($f['estado']) ?>"><?= htmlspecialchars($f['estado']) ?></span><b>$<?= number_format((float)$f['total'],2) ?></b><em>Ver recibo →</em></div></a><?php endforeach; ?></div></div>
<div class="section-spacer"><div class="section-heading"><div><div class="eyebrow">Movimientos</div><h2>Historial de pagos</h2></div></div><table class="table"><thead><tr><th>Fecha</th><th>Referencia</th><th>Factura</th><th>Método</th><th>Monto</th><th></th></tr></thead><tbody><?php foreach($pagos as $p): ?><tr><td><?= htmlspecialchars(substr($p['creado'],0,10)) ?></td><td><?= htmlspecialchars($p['referencia']) ?></td><td><?= htmlspecialchars($p['factura_folio']??'—') ?></td><td><?= htmlspecialchars($p['metodo']) ?></td><td>$<?= number_format((float)$p['monto'],2) ?></td><td><a href="/comprobante.php?id=<?= $p['id'] ?>">Ver</a></td></tr><?php endforeach; ?></tbody></table></div>
<?php endif; ?></div></div></div></section>
<?php include __DIR__.'/includes/footer.php'; ?>
