<?php
$pageTitle='Informes anuales';
$manifestPath=__DIR__.'/assets/informes/manifest.json';
$reports=file_exists($manifestPath)?json_decode(file_get_contents($manifestPath),true):[];
$latest=array_values(array_filter($reports,fn($r)=>$r['year']>=2022));
$eras=[
 '1978–1989'=>array_filter($reports,fn($r)=>$r['year']<=1989),
 '1990–2004'=>array_filter($reports,fn($r)=>$r['year']>=1990&&$r['year']<=2004),
 '2005–2014'=>array_filter($reports,fn($r)=>$r['year']>=2005&&$r['year']<=2014),
 '2015–2021'=>array_filter($reports,fn($r)=>$r['year']>=2015&&$r['year']<=2021),
];
include __DIR__.'/includes/header.php';
?>
<section class="reports-hero"><div class="wrap"><div class="eyebrow">Archivo institucional · 1978–2026</div><h1>Informes anuales de gestión y resultados</h1><p>Consulta la evolución del organismo a través de sus memorias administrativas, informes de gestión, indicadores de desempeño y resultados del Plan Metropolitano de Desarrollo Hídrico.</p><div class="report-hero-actions"><a class="btn" target="_blank" rel="noopener" href="/assets/informes/informe-anual-2026.pdf">Consultar Informe 2026</a><a class="btn btn-outline" href="#archivo">Explorar archivo histórico</a></div></div></section>
<section class="section"><div class="wrap"><div class="section-heading"><div><div class="eyebrow">Plan Metropolitano 2022–2026</div><h2>Informes orientados a ejes, acciones y resultados</h2><p>Los informes recientes vinculan metas, inversión y desempeño con cinco ejes de desarrollo.</p></div></div><div class="report-axis-grid"><article><span>01</span><b>Agua segura y continuidad</b><p>Abasto, presión, cobertura e interrupciones.</p></article><article><span>02</span><b>Saneamiento y resiliencia</b><p>Tratamiento, alcantarillado y adaptación.</p></article><article><span>03</span><b>Infraestructura y eficiencia</b><p>Rehabilitación, energía, pérdidas y medición.</p></article><article><span>04</span><b>Gobierno abierto y ciudadanía</b><p>Atención, datos, trámites y transparencia.</p></article><article><span>05</span><b>Innovación y transformación digital</b><p>Telemetría, automatización y resiliencia tecnológica.</p></article></div><div class="latest-report-grid section-spacer"><?php foreach(array_reverse($latest) as $r): ?><article class="annual-report-card report-modern"><div><small>Informe Metropolitano</small><strong><?= (int)$r['year'] ?></strong><span><?= htmlspecialchars($r['subtitle']) ?></span></div><div class="report-card-links"><a target="_blank" rel="noopener" href="<?= htmlspecialchars($r['file']) ?>">Consultar ↗</a><a download href="<?= htmlspecialchars($r['file']) ?>">Descargar ↓</a></div></article><?php endforeach; ?></div></div></section>
<section class="section section-soft" id="archivo"><div class="wrap"><div class="section-heading"><div><div class="eyebrow">Memoria institucional</div><h2>Archivo histórico de informes anuales</h2></div></div><?php foreach($eras as $label=>$items): ?><div class="report-era"><div class="report-era-head"><h3><?= htmlspecialchars($label) ?></h3><span><?= count($items) ?> informes</span></div><div class="archive-report-grid"><?php foreach(array_reverse($items) as $r): ?><article class="archive-report-item"><strong><?= (int)$r['year'] ?></strong><span><?= htmlspecialchars($r['title']) ?></span><small><?= htmlspecialchars($r['subtitle']) ?></small><div class="archive-report-links"><a target="_blank" rel="noopener" href="<?= htmlspecialchars($r['file']) ?>">Consultar ↗</a><a download href="<?= htmlspecialchars($r['file']) ?>">Descargar ↓</a></div></article><?php endforeach; ?></div></div><?php endforeach; ?></div></section>
<?php include __DIR__.'/includes/footer.php'; ?>
