<?php
$pageTitle='Organización'; require_once __DIR__.'/includes/scenario.php'; $final=all_flags_obtained(); include __DIR__.'/includes/header.php';
$normal=[
['/assets/img/adrian-leclerc.svg','Dr. Adrián Leclerc Mendoza','Director General'],['/assets/img/elena-marin.svg','Elena Marín Soler','Operación Hidráulica'],['/assets/img/gabriel-monteiro.svg','Gabriel Monteiro Vega','Saneamiento'],['/assets/img/laura-bianchi.svg','Laura Bianchi Romero','Tecnologías e Innovación'],['/assets/img/marc-dubois.svg','Marc Dubois Hernández','Jurídica'],['/assets/img/sofia-costa.svg','Sofía Costa Navarro','Administración'],['/assets/img/daniel-moreau.svg','Daniel Moreau Salazar','Atención Ciudadana'],['/assets/img/isabelle-laurent.svg','Isabelle Laurent Castro','Monitoreo Operacional']];
$interinos=[
['','Mtra. Valeria Serrano Cruz','Encargada de Despacho · Dirección General'],['','Ing. Tomás Rivas Calderón','Encargado de Despacho · Operación Hidráulica'],['','Mtra. Renata Vidal Moreau','Encargada de Despacho · Saneamiento'],['','Ing. Bruno Ferrer Lozano','Encargado de Despacho · Tecnologías e Innovación'],['','Lic. Camila Ortega Neri','Encargada de Despacho · Jurídica'],['','C.P. Héctor Salvatierra Ruiz','Encargado de Despacho · Administración'],['','Mtra. Natalia Correa Vidal','Encargada de Despacho · Atención Ciudadana'],['','Ing. Emilio Navarro Costa','Encargado de Despacho · Monitoreo Operacional']];
$people=$final?$interinos:$normal;
?>
<section class="section"><div class="wrap"><div class="eyebrow">Estructura institucional</div><h1><?= $final?'Estructura provisional de continuidad':'Organización institucional' ?></h1><p class="section-intro"><?= $final?'Tras las separaciones y suspensiones derivadas de la crisis, el organismo opera temporalmente mediante encargadurías de despacho mientras concluyen las investigaciones.':'La estructura institucional coordina operación, tecnología, cumplimiento, atención y gestión de incidentes.' ?></p><?php if($final): ?><div class="notice crisis-org"><b>Actualización extraordinaria</b><p>Las designaciones son provisionales y permanecerán vigentes hasta que los órganos competentes determinen responsabilidades y nuevos nombramientos.</p></div><?php endif; ?><div class="org-chart"><div class="org-root"><?php $r=array_shift($people); if($r[0]):?><img src="<?=htmlspecialchars($r[0])?>" alt="Retrato institucional"><?php else:?><span class="org-initial"><?=htmlspecialchars(mb_substr($r[1],0,1))?></span><?php endif;?><b><?=htmlspecialchars($r[1])?></b><span><?=htmlspecialchars($r[2])?></span></div><div class="org-branches"><?php foreach($people as $x):?><div><?php if($x[0]):?><img src="<?=htmlspecialchars($x[0])?>" alt="Retrato institucional"><?php else:?><span class="org-initial"><?=htmlspecialchars(mb_substr($x[1],0,1))?></span><?php endif;?><b><?=htmlspecialchars($x[1])?></b><span><?=htmlspecialchars($x[2])?></span></div><?php endforeach;?></div></div></div></section>
<section class="section soft-section"><div class="wrap"><div class="section-heading"><div><div class="eyebrow">Capital humano</div><h2>486 personas sostienen el servicio</h2></div></div><div class="stat-grid"><div class="stat-card"><b>238</b><span>Operación</span></div><div class="stat-card"><b>74</b><span>Ingeniería y tecnología</span></div><div class="stat-card"><b>58</b><span>Atención ciudadana</span></div><div class="stat-card"><b>72</b><span>Administración</span></div><div class="stat-card"><b>18</b><span>Jurídico y cumplimiento</span></div><div class="stat-card"><b>26</b><span>Dirección y coordinación</span></div></div></div></section>
<?php include __DIR__.'/includes/footer.php'; ?>