<?php
require __DIR__.'/includes/config.php'; if(empty($_SESSION['user'])){header('Location:/login.php');exit;}$pdo=db();$uid=(int)$_SESSION['user']['id'];
$q=$pdo->prepare('SELECT * FROM cuentas_servicio WHERE usuario_id=? ORDER BY id LIMIT 1');$q->execute([$uid]);$c=$q->fetch();$q=$pdo->prepare('SELECT COUNT(*) FROM cuentas_servicio WHERE usuario_id=?');$q->execute([$uid]);$serviceCount=(int)$q->fetchColumn();
$q=$pdo->prepare('SELECT * FROM expedientes WHERE usuario_id=? ORDER BY fecha DESC,id DESC LIMIT 1');$q->execute([$uid]);$e=$q->fetch();
$q=$pdo->prepare('SELECT COUNT(*) FROM documentos WHERE usuario_id=?');$q->execute([$uid]);$docCount=(int)$q->fetchColumn();
$q=$pdo->prepare('SELECT COUNT(*) FROM notificaciones WHERE usuario_id=? AND leida=0');$q->execute([$uid]);$notifCount=(int)$q->fetchColumn();
$invoice=null;$cons=[];$payments=[];$notes=[];
if($c){$q=$pdo->prepare("SELECT * FROM facturas WHERE cuenta_id=? AND estado<>'Pagada' ORDER BY fecha_emision DESC LIMIT 1");$q->execute([$c['id']]);$invoice=$q->fetch();$q=$pdo->prepare('SELECT * FROM consumos WHERE cuenta_id=? ORDER BY periodo ASC');$q->execute([$c['id']]);$cons=$q->fetchAll();$q=$pdo->prepare('SELECT * FROM pagos WHERE cuenta_id=? ORDER BY creado DESC LIMIT 2');$q->execute([$c['id']]);$payments=$q->fetchAll();}
$q=$pdo->prepare('SELECT * FROM notificaciones WHERE usuario_id=? ORDER BY fecha DESC LIMIT 3');$q->execute([$uid]);$notes=$q->fetchAll();
$pageTitle='Mi portal'; include __DIR__.'/includes/header.php';?>
<section class="section account-section"><div class="wrap"><div class="account-welcome"><div><div class="eyebrow">Portal ciudadano</div><h1>Hola, <?= htmlspecialchars(explode(' ',$_SESSION['user']['nombre'])[0]) ?></h1><p><?= $c?'Tu servicio está vinculado. Aquí tienes el estado más reciente de tu cuenta.':'Tu cuenta digital está lista. Vincula un servicio para habilitar facturación y consumo.' ?></p></div><div class="welcome-actions"><a class="notification-bell" href="/notificaciones.php">🔔 <b><?= $notifCount ?></b></a><span class="account-status"><i></i> Sesión activa</span><span class="account-status" id="accountContextStatus" data-account-context><i></i> Sincronizando cuenta</span></div></div>
<div class="account-layout"><aside class="account-sidebar"><a class="active" href="/panel.php">Resumen</a><a href="/mis-servicios.php">Mis servicios</a><a href="/lectura-medidor.php">Lectura del medidor</a><a href="/expediente.php">Mi expediente</a><a href="/facturacion.php">Facturación</a><a href="/documentos.php">Documentos</a><a href="/afectaciones.php">Mapa de afectaciones</a><a href="/notificaciones.php">Notificaciones<?= $notifCount?' · '.$notifCount:'' ?></a><a href="/perfil.php">Perfil</a><a href="/vincular-servicio.php">Vincular servicio</a><a class="logout-link" href="/logout.php">Cerrar sesión</a></aside><div>
<?php if(isset($_GET['nuevo'])): ?><div class="success-banner">Tu cuenta fue creada correctamente. <?= $c?'El servicio también quedó vinculado.':'Ahora puedes vincular tu cuenta de servicio.' ?></div><?php endif; ?>
<?php if(!$c): ?><div class="onboarding-card"><div><span>01</span><h2>Vincula tu servicio</h2><p>Ingresa el número de cuenta que aparece en tu recibo para consultar consumo, facturas y pagos.</p><a class="btn" href="/vincular-servicio.php">Vincular ahora</a></div><div class="onboarding-steps"><p><b>Después podrás:</b></p><span>✓ Consultar recibos</span><span>✓ Revisar consumos</span><span>✓ Pagar en línea</span><span>✓ Descargar comprobantes</span></div></div><?php else: ?>
<div class="service-hero-card"><div><small>CUENTA <?= htmlspecialchars($c['cuenta']) ?></small><h2><?= htmlspecialchars($c['domicilio']) ?></h2><p><?= htmlspecialchars($c['colonia'].', '.$c['municipio']) ?> · <?= htmlspecialchars($c['tarifa']) ?></p></div><div><small>Saldo actual</small><b>$<?= number_format((float)$c['saldo'],2) ?></b><a href="/pago.php">Pagar ahora →</a></div></div>
<div class="portal-kpis section-spacer"><div><b><?= $serviceCount ?></b><span>Servicios vinculados</span></div><div><b><?= $e&&$e['estatus']!=='Concluido'?1:0 ?></b><span>Trámite activo</span></div><div><b><?= $docCount ?></b><span>Documentos</span></div><div><b><?= $invoice?'1':'0' ?></b><span>Recibo pendiente</span></div><div><b><?= $notifCount ?></b><span>Notificaciones</span></div></div>
<div class="portal-grid section-spacer"><a href="/mis-servicios.php"><small>SERVICIOS</small><h3><?= $serviceCount ?> vinculados</h3><p>Administra cuentas, medidores y domicilios.</p><span>Administrar →</span></a><a href="/lectura-medidor.php"><small>MEDIDOR</small><h3>Enviar lectura</h3><p>Captura la lectura y adjunta una fotografía.</p><span>Capturar →</span></a><a href="/afectaciones.php"><small>SERVICIO</small><h3>Mapa de afectaciones</h3><p>Consulta trabajos, fugas y mantenimientos activos.</p><span>Ver mapa →</span></a><a href="/expediente.php"><small>EXPEDIENTE</small><h3><?= htmlspecialchars($e['folio']??'Sin expediente') ?></h3><p><?= htmlspecialchars(($e['tipo']??'—').' · '.($e['estatus']??'—')) ?></p><span>Consultar →</span></a><a href="/facturacion.php"><small>FACTURACIÓN</small><h3><?= $invoice?'$'.number_format((float)$invoice['saldo'],2):'Al corriente' ?></h3><p><?= $invoice?'Recibo '.$invoice['periodo'].' pendiente':'No tienes recibos pendientes' ?></p><span>Ver historial →</span></a><a href="/documentos.php"><small>DOCUMENTOS</small><h3><?= $docCount ?> disponibles</h3><p>Constancias, acuses y documentos de tu cuenta.</p><span>Ver documentos →</span></a></div>
<?php if($cons): $max=max(array_column($cons,'consumo_m3')); ?><div class="dashboard-consumption section-spacer"><div><div class="eyebrow">Consumo</div><h2>Tu consumo reciente</h2><p>Últimos seis periodos · promedio de zona como referencia.</p><a href="/facturacion.php">Ver detalle →</a></div><div class="mini-consumption-chart"><?php foreach($cons as $co): $h=max(20,round(($co['consumo_m3']/$max)*100)); ?><div><i style="height:<?= $h ?>%"></i><b><?= number_format((float)$co['consumo_m3'],1) ?></b><span><?= htmlspecialchars(substr($co['periodo'],5,2)) ?></span></div><?php endforeach; ?></div></div><?php endif; ?>
<div class="dashboard-bottom section-spacer"><div class="activity-panel"><div><h3>Actividad reciente</h3><p>Últimos movimientos registrados.</p></div><ul><?php foreach($payments as $p): ?><li><span><?= htmlspecialchars(date('d M',strtotime($p['creado']))) ?></span>Pago aplicado · $<?= number_format((float)$p['monto'],2) ?></li><?php endforeach; ?><?php if($e): ?><li><span><?= htmlspecialchars(date('d M',strtotime($e['fecha']))) ?></span><?= htmlspecialchars($e['tipo']) ?> · <?= htmlspecialchars($e['estatus']) ?></li><?php endif; ?></ul></div><div class="notification-preview"><div><h3>Avisos</h3><a href="/notificaciones.php">Ver todos</a></div><?php foreach($notes as $n): ?><a href="/notificaciones.php"><small><?= htmlspecialchars($n['tipo']) ?></small><b><?= htmlspecialchars($n['titulo']) ?></b><span><?= htmlspecialchars($n['mensaje']) ?></span></a><?php endforeach; ?></div></div>
<?php endif; ?></div></div></div></section>
<?php include __DIR__.'/includes/footer.php'; ?>
