<?php
require __DIR__.'/includes/config.php'; lab_sensitive_page('proveedores.php','Padrón de proveedores');
$q=trim($_GET['q']??''); $page=max(1,(int)($_GET['page']??1)); $per=25; $offset=($page-1)*$per;
$where=''; $params=[]; if($q!==''){ $where=' WHERE nombre LIKE ? OR servicio LIKE ? '; $params=['%'.$q.'%','%'.$q.'%']; }
$ct=db()->prepare('SELECT COUNT(*) FROM proveedores'.$where); $ct->execute($params); $total=(int)$ct->fetchColumn();
$sql='SELECT id,nombre,servicio,estado FROM proveedores'.$where.' ORDER BY nombre LIMIT '.$per.' OFFSET '.$offset; $st=db()->prepare($sql); $st->execute($params); $rows=$st->fetchAll(); $pages=max(1,(int)ceil($total/$per));
$pageTitle='Proveedores'; include __DIR__.'/includes/header.php'; ?>
<section class="section"><div class="wrap"><div class="eyebrow">Relación con terceros</div><h1>Padrón de proveedores</h1><p class="section-intro">Consulta el padrón vigente, tipo de servicio y situación del registro. El listado completo contiene <?= number_format($total) ?> registros.</p><div class="stat-grid"><div class="stat-card"><b>219</b><span>Proveedores registrados</span></div><div class="stat-card"><b>27</b><span>Tecnológicos</span></div><div class="stat-card"><b>41</b><span>Mantenimiento</span></div><div class="stat-card"><b>33</b><span>Acceso a instalaciones</span></div></div>
<div class="search-panel section-spacer"><div><div class="eyebrow">Padrón completo</div><h2>Buscar proveedor</h2><p>Nombre, especialidad o servicio contratado.</p></div><form method="get" class="search-form"><input name="q" value="<?= htmlspecialchars($q) ?>" placeholder="Nombre o servicio"><button class="btn">Buscar</button><a class="btn btn-light" href="/exportar.php?tipo=proveedores">CSV</a></form></div>
<div class="table-toolbar"><span>Mostrando <?= $total?($offset+1):0 ?>-<?= min($offset+$per,$total) ?> de <?= $total ?></span><div><a class="text-link" href="/contrataciones.php">Ver 143 contrataciones →</a> · <a class="text-link" href="/gestion-proveedores.php">Área de gestión · personal autorizado →</a></div></div><table class="table"><thead><tr><th>ID</th><th>Proveedor</th><th>Servicio</th><th>Estado</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?= (int)$r['id'] ?></td><td><b><?= htmlspecialchars($r['nombre']) ?></b></td><td><?= htmlspecialchars($r['servicio']) ?></td><td><span class="tag<?= $r['estado']==='Vigente'?' tag-green':'' ?>"><?= htmlspecialchars($r['estado']) ?></span></td></tr><?php endforeach; ?></tbody></table>
<div class="pagination"><?php for($i=1;$i<=$pages;$i++): if($i==1||$i==$pages||abs($i-$page)<=2): ?><a class="<?= $i===$page?'active':'' ?>" href="?q=<?= urlencode($q) ?>&page=<?= $i ?>"><?= $i ?></a><?php elseif($i==2 && $page>4 || $i==$pages-1 && $page<$pages-3): ?><span>…</span><?php endif; endfor; ?></div></div></section>
<?php include __DIR__.'/includes/footer.php'; ?>