<?php $pageTitle='Quiénes somos'; include __DIR__.'/includes/header.php'; ?>
<section class="media-hero"><div class="wrap media-hero-grid"><div><div class="eyebrow">Institucional</div><h1>Quiénes somos</h1><p>INTERAFAS coordina la prestación de servicios de agua potable, alcantarillado y saneamiento con enfoque metropolitano, continuidad operacional y atención ciudadana.</p></div><img src="/assets/img/support-team.svg" alt="Equipo institucional"></div></section>
<section class="section"><div class="wrap two-col"><div><div class="eyebrow">Misión</div><h2>Gestionar agua con visión metropolitana</h2><p>Prestar servicios esenciales mediante infraestructura, conocimiento técnico, atención ciudadana y coordinación entre municipios.</p></div><div><div class="eyebrow">Visión</div><h2>Una red resiliente y medible</h2><p>Integrar operación, mantenimiento, información y transparencia para sostener servicios confiables frente a cambios y contingencias.</p></div></div><div class="principle-grid section-spacer"><div><b>Continuidad</b><span>Servicio esencial</span></div><div><b>Resiliencia</b><span>Preparación y recuperación</span></div><div><b>Transparencia</b><span>Información pública</span></div><div><b>Eficiencia</b><span>Medición y mejora</span></div><div><b>Servicio</b><span>Atención ciudadana</span></div></div></div></section>
<section class="section soft-section"><div class="wrap"><div class="eyebrow">Trayectoria institucional</div><h2>Una organización que fue cambiando con la ciudad</h2><p class="section-intro">La infraestructura actual es resultado de casi cinco décadas de expansión urbana, coordinación intermunicipal, saneamiento, medición y modernización operacional.</p><div class="timeline-rich">
<div><b>1978</b><span>Primer sistema coordinado de abastecimiento</span><p>Se formaliza la operación conjunta de pozos, redes primarias y atención a usuarios en la zona urbana central.</p></div>
<div><b>1984</b><span>Primera planta de tratamiento regional</span><p>Inicia una etapa de saneamiento con infraestructura dedicada al tratamiento de aguas residuales.</p></div>
<div><b>1992</b><span>Interconexión de redes municipales</span><p>Se construyen líneas de conducción que permiten transferir caudal entre sectores durante contingencias y mantenimiento.</p></div>
<div><b>1998</b><span>Automatización del bombeo principal</span><p>Las estaciones de mayor capacidad incorporan control electromecánico, alarmas y registro de variables.</p></div>
<div><b>2004</b><span>Centro de operación hidráulica</span><p>Se concentran guardias, coordinación de maniobras y seguimiento de presiones, niveles y caudales.</p></div>
<div><b>2008</b><span>Nace el organismo intermunicipal</span><p>La operación se reorganiza bajo un modelo metropolitano para compartir capacidades, planeación y recursos.</p></div>
<div><b>2012</b><span>Ampliación del saneamiento</span><p>Entran en operación nuevos trenes de tratamiento y programas de reúso para actividades productivas.</p></div>
<div><b>2014</b><span>Integración metropolitana</span><p>Se homologa la gestión de usuarios, mantenimiento y planeación de infraestructura entre los tres municipios.</p></div>
<div><b>2017</b><span>Sectorización y cartografía digital</span><p>La red comienza a administrarse mediante distritos hidráulicos, macromedición y un sistema geográfico institucional.</p></div>
<div><b>2019</b><span>Modernización de saneamiento</span><p>Se actualizan procesos, equipos de laboratorio y esquemas de control para mejorar eficiencia y calidad.</p></div>
<div><b>2021</b><span>Atención ciudadana digital</span><p>Trámites, reportes, recibos y constancias migran gradualmente a canales digitales.</p></div>
<div><b>2023</b><span>Programa de telemetría</span><p>Instalaciones estratégicas incorporan monitoreo remoto de niveles, caudal, presión, energía y estado de equipos.</p></div>
<div><b>2025</b><span>Resiliencia y continuidad operacional</span><p>Se formalizan programas de respaldo, operación alternativa, mantenimiento por criticidad y gestión de riesgos.</p></div>
<div><b>2026</b><span>Observatorio Hídrico Metropolitano</span><p>Indicadores operativos, comerciales, energéticos y de servicio se integran para consulta pública y toma de decisiones.</p></div>
</div></div></section>
<?php include __DIR__.'/includes/footer.php'; ?>