<?php
$pageTitle='Conversación digital';
require_once __DIR__.'/includes/scenario.php';
$s=scenario_state();
$q=db()->prepare("SELECT p.*, CASE WHEN p.event_required IS NOT NULL THEN COALESCE((SELECT MAX(se.created_at) FROM scenario_events se WHERE se.event_code=p.event_required), '2000-01-01 00:00:00') ELSE CASE p.phase_required WHEN 0 THEN DATE_ADD('2026-09-23 08:00:00', INTERVAL p.id SECOND) WHEN 1 THEN DATE_ADD(COALESCE((SELECT MAX(se.created_at) FROM scenario_events se WHERE se.event_code='FLAG_16'),'2026-09-23 09:00:00'), INTERVAL p.delay_seconds SECOND) WHEN 2 THEN DATE_ADD(COALESCE((SELECT MAX(se.created_at) FROM scenario_events se WHERE se.event_code='FLAG_17'),'2026-09-23 10:00:00'), INTERVAL p.delay_seconds SECOND) WHEN 3 THEN DATE_ADD(COALESCE((SELECT MAX(se.created_at) FROM scenario_events se WHERE se.event_code='FLAG_18'),'2026-09-23 12:00:00'), INTERVAL p.delay_seconds SECOND) WHEN 4 THEN DATE_ADD(COALESCE((SELECT MAX(se.created_at) FROM scenario_events se WHERE se.event_code='FLAG_20'),'2026-09-23 16:00:00'), INTERVAL p.delay_seconds SECOND) WHEN 5 THEN DATE_ADD(COALESCE((SELECT MAX(se.created_at) FROM scenario_events se WHERE se.event_code='RECOVERY_STARTED'),'2026-09-23 18:00:00'), INTERVAL p.delay_seconds SECOND) ELSE '2000-01-01 00:00:00' END END AS visible_at FROM scenario_social_posts p WHERE ((p.event_required IS NULL AND (p.phase_required < ? OR (p.phase_required=? AND p.delay_seconds<=?))) OR (p.event_required IS NOT NULL AND EXISTS (SELECT 1 FROM scenario_events se WHERE se.event_code=p.event_required))) ORDER BY visible_at DESC,p.id DESC");
$q->execute([(int)$s['phase'],(int)$s['phase'],(int)$s['elapsed_seconds']]);
$posts=$q->fetchAll();
include __DIR__.'/includes/header.php';
?>
<section class="media-hero social-hero"><div class="wrap media-hero-grid"><div><div class="eyebrow">Conversación digital</div><h1>Lo que la ciudad dice<br>también forma parte del servicio.</h1><p>Una conversación abierta: servicio público, vida cotidiana, humor, crítica, apoyo, política y todo lo que termina mezclándose en una red social.</p><div class="social-hero-badges"><span>Facebook</span><span>X</span><span>Instagram</span><span>TikTok</span></div></div><div class="social-radar-card"><small>Estado de conversación</small><b><?= htmlspecialchars($s['phase_name']) ?></b><span><?= count($posts) ?> publicaciones visibles</span><div class="live-pulse-line"><i></i>Actualización automática</div></div></div></section>
<section class="section soft-section"><div class="wrap"><div class="section-heading compact"><div><div class="eyebrow">Publicaciones</div><h2>Conversación reciente</h2><p>Las publicaciones se acumulan conforme evoluciona la conversación metropolitana. Las más recientes aparecen primero.</p></div></div>
<div class="social-feed" id="socialFeed">
<?php foreach($posts as $i=>$p): $age = $p['phase_required']==$s['phase'] ? 0 : min(30, max(1, ((int)$s['phase']-(int)$p['phase_required'])*2)); $postTime=!empty($p['visible_at'])?date('H:i',strtotime($p['visible_at'])):''; ?>
<article class="social-post" data-age="<?= $age ?>"><div class="social-avatar-photo generated-avatar"><?php if(!empty($p['avatar_url'])): ?><img src="<?= htmlspecialchars($p['avatar_url']) ?>" alt="Perfil de <?= htmlspecialchars($p['display_name']) ?>" onerror="this.style.display='none'" loading="lazy"><?php endif; ?><span><?= htmlspecialchars(mb_strtoupper(mb_substr($p['display_name'],0,1))) ?></span></div><div><div class="social-meta"><b><?= htmlspecialchars($p['handle']) ?></b><span>· <?= $postTime ? htmlspecialchars($postTime) : ($p['phase_required']==$s['phase'] ? 'hace unos minutos' : ($age==1?'ayer':$age.' días')) ?><?= $p['municipality']?' · '.htmlspecialchars($p['municipality']):'' ?></span></div><p><?= htmlspecialchars($p['content']) ?></p><?php if(!empty($p['meme_title'])): ?><div class="social-meme"><b><?= htmlspecialchars($p['meme_title']) ?></b><span><?= htmlspecialchars($p['meme_caption'] ?? '') ?></span></div><?php endif; ?><div class="social-actions"><span>♡ <?= (int)$p['likes'] ?></span><span>↻ <?= (int)$p['shares'] ?></span><span>Responder</span></div></div></article>
<?php endforeach; ?>
</div></div></section>
<section class="section"><div class="wrap"><div class="section-heading"><div><div class="eyebrow">Cobertura externa</div><h2>También está cambiando la conversación fuera del portal</h2></div><p>Consulta la cobertura que se va publicando conforme evoluciona la situación.</p></div><a class="external-news-card" href="http://localhost:<?= htmlspecialchars(getenv('NEWS_PORT') ?: '8091') ?>" target="_blank" rel="noopener"><span>Pulso Metropolitano</span><b>Abrir cobertura en vivo ↗</b></a></div></section>
<script>window.INTERAFAS_SCENARIO_POLL=true;</script>
<?php include __DIR__.'/includes/footer.php'; ?>